### ISSUE TITLE
Reference for cached values is back again

### ISSUE THREAD

**Issue by grziwok** [formio/formio.js#1003]
At the end of the December @kamilogerto2 prepared a pull request https://github.com/formio/formio.js/pull/896 which was merged. We updated form.io packages yesterday and this issue is back again because changes were reverted in https://github.com/formio/formio.js/pull/964. `cloneDeep` which was used there was necessary in our case to show submit button properly when changing `viewOnly` mode.

I guess there was some other issues related to that, however is it possible to give us more information why it was reverted? We would be grateful to cover our case too.

**Comment by travist** [comment]
There were really two things that were changed from your original update.

 1.) We need to returned a resolved promise so ```return Promise.resolve``` was added @ https://github.com/formio/formio.js/blob/master/src/Formio.js#L701

 2.) We removed the additional ```_.cloneDeep``` when the values are placed into cache @ https://github.com/formio/formio.js/blob/master/src/Formio.js#L825

We need to keep the change from 1 since this is needed to keep the method return type consistent.

The change to 2.) is negotiable. I removed the ```_.cloneDeep``` there because you added the ```_.cloneDeep``` to the point when the cached item is returned. I removed the other cloneDeep because it was redundant and was basically double copying. The assumption I made here is that there should not be any external references to the actual Formio.cache object but rather that would be retrieved when making the request call (which is then handled because a clone is made on the way out).  Let me know why my assumption was wrong and we will work with you on getting a resolution that will work with your use case as well.

**Comment by grziwok** [comment]
Thanks for explanation @travist. I don't mind the first change - it makes sense to me.
Regarding the change to 2, I'm afraid that when we return cached object, it still holds a reference but to cached object. So external reference still exists and breaks rendering of form with same id when switching `viewOnly` and `readOnly` dynamically.

Adding `cloneDeep` would fix our issue with missing submit button, let me know if that works for you. Unless I could prepare a demo app for you to show you the problem.

**Comment by travist** [comment]
The issue may be that the Promise.resolve() stores the value and returns the same instance everytime. I would need to investigate further. So are you saying that when you add ```_.cloneDeep``` to the setting of the cache, that it fixes your problem? I would be willing to add that back, but removed it since it seemed like it was not needed and a performance hit.

**Comment by kamilogerto2** [comment]
Hi @travist.

Maybe I am wrong but I thing that cache should be indepenent as much as possible so if there is any possibility to hold reference - we need to cut it. This additionally cloneDeep resolve our problem but I am intereseted of your sentence about performance. Which performance issues could happen here? Also as @grziwok said - the problem appears when we use the same form in different mode. Maybe you can add this case scenario to tests? For us this is the easiest way to resolve that problem but I know that you are much better in this platform and you can find another solution if needed ;) We know that the problem exists and we know only simplest solution for that. 

If you need any help with that or more details - let us know. We were only suprised when our app was broken in the same way as earlier after upgrading a version. ;)

**Comment by grziwok** [comment]
@travist Did you have opportunity to look into this issue? Yes, `_.cloneDeep` solves our problem.

**Comment by travist** [comment]
@grziwok we will fix this with next release. Should be able to get that our today or over the weekend.

**Comment by grziwok** [comment]
@travist, I've just tested it and it works well. Thank you 👍
