### ISSUE TITLE
Bug: Select component does not build querystring parameters correctly with formio.js

### ISSUE THREAD

**Issue by 1100617** [formio/formio.js#1135]
I've configured a select component in formio builder with this configuration:

![formio_select_dropdown_bug4](https://user-images.githubusercontent.com/2955373/55559838-f4bcee00-56e6-11e9-9f7f-1772a5debdc1.PNG)

The component was defined to load data via URL. "Search Query Name" and "Limit" were set. When the form is rendered in formio builder (Angular), it builds the querystring parameters as expected. Example:

When I type "para":
![formio_select_dropdown_bug5](https://user-images.githubusercontent.com/2955373/55560165-95131280-56e7-11e9-9158-46f1e0647389.PNG)

The request is correct as well as the querystring parameters. (name = "para", limit = 10, skip = 0)

![formio_select_dropdown_bug2](https://user-images.githubusercontent.com/2955373/55559883-07cfbe00-56e7-11e9-8926-a99ab782688a.PNG)

When the same form is rendered via formio.js, the querystring parameters are different and incorrect.
Instead of using the defined "Search Query Name", it adds the suffix "__regex".
It ignores the "limit" and  "skip" query parameter.

![formio_select_dropdown_bug3](https://user-images.githubusercontent.com/2955373/55560019-44031e80-56e7-11e9-8b18-45f57d2f8f31.PNG)

**Comment by mtpersonalfile** [comment]
I'm experiencing the same issue. Any progress on this, or workaround, until this is fixed?

**Comment by franke-mc** [comment]
The code appears to be in [src/components/select/Select.js](https://github.com/formio/formio.js/blob/master/src/components/select/Select.js#L389):
```
    const limit = this.component.limit || 100;
    const skip = this.isScrollLoading ? this.selectOptions.length : 0;
    const query = (this.component.dataSrc === 'url') ? {} : {
      limit: limit,
      skip: skip
    };

    // Allow for url interpolation.
    url = this.interpolate(url, {
      formioBase: Formio.getBaseUrl(),
      search,
      limit,
      skip,
      page: Math.abs(Math.floor(skip / limit))
    });
```
Have you tried adding `?limit={{limit}}&skip={{skip}}` to the url? Does that work?

(The `__regex` suffix is added to the search parameter a few lines below, probably to approximate something like case-insensitive substring search.)

**Comment by randallknutson** [comment]
You are correct. We shouldn't be doing that in the Select component as it limits functionality. These lines should be changed back to how it worked in ngFormio where it doesn't automatically append the __regex or __in. 

https://github.com/formio/formio.js/blob/master/src/components/select/Select.js#L404-L411

**Comment by franke-mc** [comment]
I understand you are referring to [this commit](https://github.com/formio/formio.js/commit/79b45e5f9bbc4eb831919aa8296dcaeb9b342f6d).
Ok; let me just point out that `searchField` has aquired a pretty complex semantics:
- Right now, it is really expected to contain only a single field name (which I deduced exactly from the its use in the code we are talking about, and which is considered a bug now).
- It had already been overloaded as a boolean: when left blank, it caused the internal, client-side search mechanism to trigger (since May 2018), [see this commit](https://github.com/formio/formio.js/commit/bc9a85da18a2bd8a11a643f17e0d4371dbd2a750).
- Based on that, I had recently added the code that would allow its use in the construction of the `searchFields` list for that client-side search mechanism, [see here.](https://github.com/formio/formio.js/commit/6616ceae6299c201faa4fc0f9b2b587881ff7fae#diff-d8fc1e0640335585f45d7a1c8be83bcd)
But beware, that code currently does not have any effect: Whenever `searchField` is set and thus can be used to construct the `value.something` for `searchFields`, the client-side search is completely disabled via `searchChoices` being false.  In effect, whenever the client-side search is used, the `searchFields` are those configured in the component (no idea if they ever had a config UI), or `['label']`.

If this stuff is to be touched again, I'd love to see a clean design of the intended semantics.

**Comment by franke-mc** [comment]
- And one more thing: By now, `selectField` is used in the config UI for the Resource component, too
[(see here).](https://github.com/formio/formio.js/commit/9c5290622c55cf46f0be2a164b61fe53100bb2e6)

**Comment by randallknutson** [comment]
Agreed. Have you looked at the version in 4.x yet? It may be a bit cleaner.

**Comment by franke-mc** [comment]
What is the intended semantics of `searchField` in 4.x? How is search config & implementation different from 3.x?

**Comment by randallknutson** [comment]
It is intended to work very similarly but if I remember correctly I reverted the searchField behavior back to how it worked without appending __regex.

**Comment by jftsaraiva** [comment]
Any workaround until this is fixed? I'm using [angular-formio](https://github.com/formio/angular-formio) - [v3.16.2](https://github.com/formio/angular-formio/releases/tag/v3.16.2)

**Comment by franke-mc** [comment]
> reverted the searchField behavior back to how it worked without appending __regex.

I don't see that [in formio.js 4.x](https://github.com/formio/formio.js/blob/4.x/src/components/select/Select.js#L325). Maybe you were thinking of something else?

**Comment by aminmc** [comment]
@randallknutson It looks like someone has added 
```js
if (this.component.searchField && search) {
      if (Array.isArray(search)) {
        query[`${this.component.searchField}__in`] = search.join(',');
      }
      else {
        query[`${this.component.searchField}__regex`] = search;
      }
    }
```

Can this be reverted?

**Comment by randallknutson** [comment]
Looks like there is a pull request for this. https://github.com/formio/formio.js/pull/1515 

We should pull this in to the next build shortly.
