### ISSUE TITLE
Date/Time validation red-border stays even if the value is selected.

### ISSUE THREAD

**Issue by ayaanraj** [formio/formio.js#1192]
Hi there,

![1rescreen](https://user-images.githubusercontent.com/29095142/56423389-79a02e00-62c9-11e9-865b-376e151f8c2f.png)

As shown in the above image, Date/Time component continues to display validation-border around input, even if the value is selected.
Strangely, this issue is only in Firefox browser only, I have tried in the different browser it works fine.

I have noticed the Date/Time component adds `pattern="\d*"` attribute to the input, if I remove that `pattern="\d*"` attribute the validation border goes out.

**Comment by randallknutson** [comment]
Do you know what version of the renderer you are using? This does seem like an issue where the Datetime component is adding that pattern when it shouldn't. Is the field type datetime or a number component with the calendar widget?

Also, you may want to use the Day component instead of Datetime/Number.

**Comment by ayaanraj** [comment]
I'm using formiojs@3.15.5 version, and the field type is DateTime.
I'm using this to collect the date, so I'm disabling the time selection.
I have done some debugging, I think in [getInputMask](https://github.com/formio/formio.js/blob/5b5863fec1397b9f9b73ac1902ce0c5e65f92fdf/src/utils/utils.js#L719)  some logic has to be changed.
My format is `dd-MM-yyyy`, in `convertFormatToMask` it is converted to `99-99-9999`, & I think `getInputMask` has to consider the `-` as well.

**Comment by travist** [comment]
If you are wanting to collect a birthday then using the DateTime component is going to be problematic. This is because this component will show the time of date in accordance with timezone specifications. What this means is that if you submit the birthday while you are located in Sydney, Australia but then read that birthday in the U.S. it will show the wrong birthday which is usually not the point with a birthday field. You should be using the Day component since it does not have this side effect.
