### ISSUE TITLE
Add datasource to formio.js

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#1308]
Hello formio,

I am using the formio.js builder local and I want to add Json resources to the form but I cannot find documentation how to.

Can you advise?

Kind regards,
Mario

**Comment by randallknutson** [comment]
Hopefully these links help:

http://formio.github.io/formio.js/app/examples/custombuilder.html
https://github.com/formio/react-app-starterkit/blob/master/src/components/CheckMatrix.js

**Comment by KyooMario** [comment]
I probably did not give you the right info. In a Select component I can choose a resource (when available).
This is the respurce I mean.
How can I add such a resource local.

Kind regards,
Mario

**Comment by randallknutson** [comment]
To add a resource for a select component, you can do so in the https://portal.form.io by going to the Resources section on the left of a project, add a new Resource and make several submissions to it.

**Comment by KyooMario** [comment]
Hello Randal,

We are using the formio.js integrated in our own solution so we don't use the portal.form.io 
So how do we use it in our integrated solution?

Kind regards,
Mario

**Comment by randallknutson** [comment]
A resource is a form with the "type" attribute of "resource". Other than that from an API perspective they are identical. You can simply create a resource type form and put some submissions in them. Once that is done it will operate identically.

**Comment by KyooMario** [comment]
Hello Randal,

Above is still too hard to understand for me. How do I create a Resource and how do I set the resource (json) objects so I can call them in a Select box. Can you give me an example?

Kind regards,
Mario

**Comment by franke-mc** [comment]
Hello Mario,
have you tried selecting "Raw JSON" instead of "Resource", and pasting the content of https://examples.form.io/company/submission as Data Source Raw JSON? Change the Item Template to item.data.name and you should have a dropdown full of resources. It's stored in the form under components.<N>.data.json , while components.<N>.dataSrc is "json".
Hope this helps.
Cheers,
Andreas

**Comment by KyooMario** [comment]
Hello Andreas,

Thanks.
I use the form in a dynamic way. I can collect the json before I create the Form (Formio.createForm) therefor I thought the "Resource" would be an option. "Raw JSON" means I have to enter the JSON in a manual way and it is static so this is not working for us.
Can you advise if a Datasource like way is possible?

Kind regards,
Mario

**Comment by randallknutson** [comment]
If you have the data available as you are embedding the form, you can preload the form definition and put your values in the datasource as data.values or something like that. The "Resource" data source is for loading the values from a Resource form url.

**Comment by franke-mc** [comment]
Alternatively, you can use "URL" as Data Source Type, and enter https://examples.form.io/company/submission as Data Source URL. Again, make sure Item Template is item.data.name.
If you can supply your items via some http get request, this should work for you.
In the form component, `dataSrc` is `"url"`, and `data.url` holds the URL string.

And regarding "Resource" as Data Source Type: As Randall said earlier, resource items ARE ordinary form submissions, so in order to create some on an ordinary formio API server, you can simply create a form with the desired fields and add some submissions. If you want to be offered that form as a Resource option in the form builder UI for the select component, you can simply change the form type from `"form"` to `"resource"` in the database. Then you are also offered the option to select "{Entire Object}" as value. In the form component, `dataSrc` is `"resource"`, and `data.resource` holds the form _id string. But I expect you don't need it; either putting your data.values into the form by hand or using the URL option above should work for you.

The data-related config options for the select component can be found [here](https://github.com/formio/formio.js/blob/master/src/components/select/editForm/Select.edit.data.js#L14).
