### ISSUE TITLE
[BUG] Day component not prepopulating data correctly

### ISSUE THREAD

**Issue by rubandangol** [formio/formio.js#1425]
There are a couple of things I would like to mention. I have checked the "hide day" checkbox in the formbuilder and therefore only the month and year gets displayed. However upon submitting the form, the submission data for the component is in mm/dd/yyyy format. And since the day field is hidden, the value for the day gets generated as 00. So basically the data is like "12/00/1999". Is this the expected result? Now the bigger issue is that when I feed the same data to the form, the year takes in the day's value and it prepopulates as 0. I am using angular-formio 3.22.0 and formiojs 3.22.10

**Comment by randallknutson** [comment]
That is currently the expected result. The issue is what we should do in the case that one of the fields is hidden. We want to keep the NN/NN/NNNN format standard so if the field is hidden we're not sure what to put there. We tried setting it to the current day/month/year but that caused issues. 

If the year is pulling the wrong value, that would be a bug and we should get it fixed. I'll add it to our backlog.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
