### ISSUE TITLE
[PDF]  source code question about  "postMessage"

### ISSUE THREAD

**Issue by kkmaojunx** [formio/formio.js#1526]
Hi ,I have a question and cannot understand  any more . So,please help me sincerly.
problem: In PDF.js  ,when i click submit button , the build function in PDF.js will  addEventListener with submit button and postMessage with params of` {name:'getSubmission'} `  `  this.addEventListener(this.submitButton, 'click', () => {
        this.postMessage({ name: 'getSubmission' });
      });`   but `window.addEventListener` get event.data is `{name:'submission'}`  the problem is I cannot find the process of transform the `getSubmission` to `submission`

**Comment by kkmaojunx** [comment]
i find the process just now . the developer set the tranform in the remote html.  So  how can i add a function. for example. if i `postMessage({name:getDraft})` and get `{name:'draft'}`?

**Comment by aiwebb** [comment]
@kkmaojunx, the messaging you're seeing here is between the parent window (in PDF.js) and the child `iframe` which actually renders the PDF. It's not currently possible to add custom listeners to the latter.

In this case, the parent window is sending a `getSubmission` message to the child `iframe`, which is then responding with a `message` event with type `submission` and a submission payload. This event is [caught by the general `message` handler and refired](https://github.com/formio/formio.js/blob/db407a0b7d672110dffb8f322c04529eee2ecb65/src/PDF.js#L198) as the `iframe-submission` event, which is handled [here](https://github.com/formio/formio.js/blob/db407a0b7d672110dffb8f322c04529eee2ecb65/src/PDF.js#L147). The parent window then actually submits the submission object generated by the child.

If you're trying to modify the Submit button behavior to submit drafts instead of normal submissions, you may want to override the `build()` function with a version that adds some custom logic to that `iframe-submission` handler and conditionally flags it as a draft submission before calling `this.submit()`.

**Comment by kkmaojunx** [comment]
@aiwebb  thanks a lot ! I  just want to add a button  next to the submit named 'draft'. so I need to distinguish this two buttons when i make click ; 
 > finally,I use `emit` and `on` to  manual trigger `iframe-submission` eventListener with different param. fortunately , it did work .  thanks again
