### ISSUE TITLE
form builder throwing error    

### ISSUE THREAD

**Issue by yaghdev** [formio/formio.js#1667]
this my code 

<div id='builder'></div>
 <script type='text/javascript'>
      window.onload = function() {
        new Formio.builder(document.getElementById('builder'));
      };
  </script>

form  builder not display giving error in console 

Cannot read property 'display' of undefined, i also attached the screenshot of it

![form_issue](https://user-images.githubusercontent.com/40377940/64693029-04b9d480-d4b4-11e9-8721-5e458d6a0a47.PNG)

**Comment by randallknutson** [comment]
What version of formio.js are you using?

**Comment by samswbk** [comment]
Same error here, last release. @randallknutson

**Comment by travist** [comment]
Last release as in 4.2.0-rc.x?

**Comment by samswbk** [comment]
formio.js-4.2.0-rc.3

**Comment by alex73630** [comment]
Hi, I had the exact same issue and after some thinkering I've found out (thanks to the non-minified version) that it is due to the fact that we aren't giving an "option" object as the second argument.

The `Formio.build` function expect to have at least an empty object as the second argument like this:
```Javascript
Formio.build(document.getElementById('builder'), {})
```

If needed, here is a working JSFiddle example: [https://jsfiddle.net/xgyvk9dh/7/](https://jsfiddle.net/xgyvk9dh/7/)

Documentation/examples should at least reflect that behaviour or function should be edited so it wouldn't force that argument to be given.

Also as a side note, it would be great to update the example to use a recent build of Bootstrap 4 as the script is compatible with it.

**Comment by aiwebb** [comment]
OK - we addressed a similar issue recently with [this commit](https://github.com/formio/formio.js/commit/0f182b0653cc0dcf26fff0a60430d66a7982dd23). I'm guessing there's a similar missing default value in this case.

If you can pinpoint where, we'd welcome a PR; otherwise, we'll add to our backlog.

**Comment by heather-formio** [comment]
Closing this thread as it is stale, please reopen if needed. Thank you for your contributions!
