### ISSUE TITLE
[Question] Form Builder: Premium components?

### ISSUE THREAD

**Issue by bobslee** [formio/formio.js#1683]
Please could you explain what the **Premium** components are about?
Seems those are available but not usable (yet)?

**Comment by wag110894** [comment]
Thanks for reaching out @bobslee.

Our Premium actions include all of our “Integration” actions which include Dropbox, Google Spreadsheets, OAuth, Office 365, etc. These actions are not available in the open source, but are available in the commercial  version of our product.

**Comment by bobslee** [comment]
Ok, thanks for clarifying this.
What about the File (upload) component? I noticed the base64 storage is still supported. We would be very happy if that stays free/open-sourced.

In fact, all those kind of file and upload components.. would be nice to support base64 in the free version.

Much appreciated!

**Comment by randallknutson** [comment]
Base64 is in the open source component since it stores in the database directly. You can use this to store the files however there are some shortcomings with this. First, the size of the submission increased significantly since the files are base64 encoded which typically nearly triples the size of the files when stored. This slows down reading submissions as well since the size is much larger. Second, our API and database both have a 16MB limit on them. You can configure to increase this but you will probably hit this limit with larger files.

**Comment by bobslee** [comment]
Thanks for answering.

**Comment by Obaidraj** [comment]
How to ignore widget in form.io
   {
                      key: "widget",
                      ignore: true,
                    },
is not working
