### ISSUE TITLE
Tab conditions

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#1773]
It is not a bug.
We would like to add conditions to tab also like we can add conditions to components.

For example, in first tab we have some questions and depending of these questions, different tabs are visible.

**Comment by nathanaelbice** [comment]
Is there any further information on how to do this, or if this will be supported at some point? This is functionality that I am interested in as well, and I'm a bit surprised that the Tabs component was not implemented as a wrapper around a tab component.

**Comment by wag110894** [comment]
@nathanaelbice, You can use our wizards to accomplish this.  Here is an example of how you can accomplish this with our Wizard: https://formio.github.io/formio.js/app/examples/conditionalwizard.html

**Comment by nathanaelbice** [comment]
@wag110894 Thanks for the suggestion, but I am actually trying to leverage this functionality within the Edit Component modal, with minimally intrusive modifications. Because of this, I believe I will need to use Tabs. I believe that I can modify the tabs component to support this, but I wanted to check for an already supported method first.

**Comment by randallknutson** [comment]
We do have this on our backlog as a feature we would like to add. If you would like to either contribute the functionality in a PR or sponsor the development of it, we'd love to get it done.

**Comment by heather-formio** [comment]
We reviewed this and are not prioritizing on our roadmap, but would welcome and contributions for this request.
