### ISSUE TITLE
Question:  Getting Started with Contributing

### ISSUE THREAD

**Issue by ps-from-md** [formio/formio.js#1811]
Is there a guide to how to set up our development environment if we want to begin contributing to pull requests and the like?  Is there a repo we can clone that is already set up so we can step through code and try to resolve our issues?

**Comment by randallknutson** [comment]
We would love some additional help from the community! 

We don't have any documentations on how to set up a dev environment specifically. The commands to do compiles and such are in the package.json "run" section. Your best bet is to set up a simple javascript environment and start the npm run watch command to recompile when you test. If there is something more specific we'd be happy to help.

**Comment by mm-dsibinski** [comment]
Hi,
I'm about to start working on a PR for [ReactFormIO #334](https://github.com/formio/react-formio/issues/334) and was wondering what would be the easiest way to work and debug the formio.js code?
I will be modifying WebformBuilder.js file. In order to do that, I cloned [formio.js repo](https://github.com/formio/formio.js). I see that if I execute ` gulp build` it outputs all bundles into the `dist` folder. I can then create a simple HTML page like this one:

```
<html>
  <head>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='c:\Yumasoft\FormIO\formio.js\dist\formio.full.min.css'>
    <script src='C:\dev\formio.js\dist\formio.full.min.js'></script>
    <script type='text/javascript'>
      window.onload = function() {
        Formio.builder(document.getElementById('builder'), {}, {});
      };
    </script>
  </head>
  <body>
    <div id='builder'></div>
  </body>
</html>
```

and it works. However, with every change in the JS files I need to re-run `gulp build` to rebuild the bundles in the `dist` folder. What's more, I can't debug JS in such a page (no source maps included I guess).
I was wondering what would be the easier way here? I'd prefer to execute `npm watch` and keep it running and recompiling everything as I make changes. However, this command only outputs files to `lib` folder - how can I include them in a page easily? Do you have any template/guide for that?

**Comment by randallknutson** [comment]
An easier way to do this is to set up an application with webpack that imports the formio library from npm instead of directly importing the dist file. Then you can run "npm run watch" in formio.js and it will dynamically rebuild the lib folder. In your app then it would see the change to the lib folder and rebuild the app as well. If you are using the dist files there is no easy way to do a dynamic update.

**Comment by mm-dsibinski** [comment]
@randallknutson yeah, finally I did like that.
Thanks :)

**Comment by SaThViK81** [comment]
Hi @mm-dsibinski,

i am using **react-formio** 

I'm about to start working on this  [issue]( https://github.com/formio/react/issues/382) may i know how to debug the code ?


Thanks for any insights.

**Comment by mm-dsibinski** [comment]
Hi @SaThViK81,
I can tell you how I did for myself. We are using `react-formio`, but in the end you are making changes in `formiojs`. `react-formio` only gives you some components for a "React-way" rendering.

I cloned the `formiojs` repository and then inside it I first executed `npm instal -g gulp-cli` to have `gulp` available. Then you might need to turn on some policies, for example by executing this command: `Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted` (you will be asked for that when trying to use the next command to build). In the end, I built `formiojs` with `gulp build` command.

Then, in our web app, I replaced `node_modules\formiojs\` contents with the contents of `formio.js\lib\` folder (after build of course). Then I'm able to put breakpoints in `formiojs` files directly in Chrome. Hope that helps!

**Comment by SaThViK81** [comment]
Thanks for the quick replay @mm-dsibinski,

i will try to the same way as you did

@mm-dsibinski  need some help to start on this [issue]( https://github.com/formio/react/issues/382)

**To have mandatory fields (need to remove edit option on hover on component) in formbuilder**

1. Add a custom property to all the components, something like "customIsMandatory", but how to add this ?

**Comment by mm-dsibinski** [comment]
Sorry @SaThViK81 , I'm not the part of FormIO team, just some occasional contributor :) You'd better ask @randallknutson I guess

**Comment by SaThViK81** [comment]
Thanks @mm-dsibinski 

@randallknutson can you please help me on that ?

**Comment by ccontour** [comment]
Hello @SaThViK81,
I am going to close this issue and replace this entry in our list of support issues with the one you linked in your comment earlier to keep your answer in context

**Comment by aananddev** [comment]
Hello @randallknutson
I am trying to setup  Formio.js in dev, I need to watch the files and Include the source map in the browser, but the package.json doesn't have any script for watch.
Do I need to setup the watch manually or is there any other way to debug.
