### ISSUE TITLE
Question: Adding custom Javascript file to add a custom component?

### ISSUE THREAD

**Issue by lailapfit** [formio/formio.js#1843]
Anyone has been successful in adding their own custom Javascript file to add a custom component to their project?

**Comment by christophermurphy2-allscripts** [comment]
There's an example provided by Formio here: https://formio.github.io/formio.js/app/examples/customcomponent.html. If you have the freedom to use es2015 or up though you can make it cleaner with:

```js
class MyComponent extends Formio.Components.components.base {
    // Override and add any behaviors you need
}

Formio.Components.addComponent('mycomponent', MyComponent);
```

You can of course extend any component just fine, but you will have to keep in mind that base might be safest since it is the least likely to change. `base` is the base class for all components, and not subject to frequent bug fixes and changes in behavior that could break your custom component.

**Comment by christophermurphy2-allscripts** [comment]
Unfortunately, I do not. If you are using Formio's hosting instead of a local setup I believe you can go to the project settings and point to a hosted javascript file, which I would assume would just need to follow the example I already gave, and also assuming Formio is already loaded onto the page. Sorry if that wasn't much help.
![image](https://user-images.githubusercontent.com/53443258/66581963-a16ca200-eb46-11e9-86a1-fc86bb6f9375.png)

**Comment by lailapfit** [comment]
No worries, thank you so much for helping! @christophermurphy2-allscripts

**Comment by lailapfit** [comment]
Update for anyone wanting to do the same, it currently works on next.form.io only!
