### ISSUE TITLE
Calendar does not hide when icon is clicked a second time

### ISSUE THREAD

**Issue by ajcolub11** [formio/formio.js#190]
Using js renderer, the calendar icon is now clickable and opens the calendar for date selection. **However, when the icon is clicked a second time, the calendar persists.**

Additionally, if the time feature is enabled on this component, then the calendar persists after date is selected. I'm not sure if this is expected or not.

**Comment by travist** [comment]
I have a fix for this coming. It was a harder fix than it sounds because the calendar automatically closes on the blur event.. What is happening is that when you click the button when the calendar is already open (such as when you close it). It actually closes it from the blur, only to be re-opened with the click of the button. The fix I am making is to only open it if it has not already just been closed.

**Comment by ajcolub11** [comment]
Excellent!! Thank you much.

**Comment by travist** [comment]
Fixed with 2.17.6
