### ISSUE TITLE
[BUG] BrowserName for Chrome browsers return Netscape

### ISSUE THREAD

**Issue by vbchrisw** [formio/formio.js#1924]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [X] Local deployment
    - Version: 3.24.3
- Formio.js version: 3.24.3
- Browser: Chrome
- Browser version: Version 77.0.3865.120 (Official Build) (64-bit)

## Steps to Reproduce
1. Submit any form

## Expected behavior
In the "metadata" stored with every form submission, I would expect to see "Chrome" as the "browserName"

## Observed behavior
FormIO gets the "browserName" using "navigator.appName" which currently returns Netscape when using a Chrome browser

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
{
	"data" : {
		"events" : [
			{
				"color" : "green",
				"event" : "Chemical"
			}
		],
		"save" : true
	},
	"metadata" : {
		"browserName" : "Netscape",
		"offset" : -300,
		"onLine" : true,
		"pathName" : "/Forms/Index/98821f8c-0d59-43d4-b2f6-951f14f0ef44",
		"referrer" : "http://localhost:51824/Admin/dc/FormsData",
		"timezone" : "America/Chicago",
		"userAgent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
	},
	"saved" : false,
	"state" : "submitted"
}
```

**Comment by randallknutson** [comment]
navigator.appName is us asking the browser what its name is. That's what Chrome tells us it is. Do you have a better suggestion where we can get the name from?

**Comment by aiwebb** [comment]
@vbchrisw Looks like Chrome and Safari both use `navigator.appName = 'Netscape'` for legacy reasons.

The browser name _is_ available in the user agent string, which is also provided, so you can certainly parse that out to get you moving today. If you're able to submit a pull request to do that [in Webform.js](https://github.com/formio/formio.js/blob/75622a71fc0719a0dd02224b887ca4baa673b86d/src/Webform.js#L1171) instead of relying on the (apparently incorrect) `appName`, we'd be happy to merge it in.

**Comment by e-gauthier** [comment]
Here is more information about this.
[](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appName)

The value of the Navigator.appName property is always "Netscape", in any browser. This property is kept only for compatibility purposes.
