### ISSUE TITLE
Columns component contains subcomponent info in two places, getting out of sync

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1936]
Using formiojs: 4.4.2
The "Columns" component appears to generate json with `.components` information in two places:
- the traditional places: in `.columns[i].components`, and
- the new place: in `.components` directly at the top level.

The new place appears to be used somewhere as everything breaks when it is removed.
But it only has a subset of the information of the traditional places, and, more seriously, is not kept in sync when the information below `.columns` changes.  This leads to all sorts of confusion, artifacts and breakage.

What's the story behind this? Why would any info need to be duplicated at all?

**Comment by travist** [comment]
The "components" object in the Columns component is intended to store the instances of all of the created components within a Nested component (which is what a Columns component is). It appears that there is duplicated effort to also keep track of the columns in the structure of multi-array which is the reason to create the separate object. I agree that this is not necessary... we could keep track of which column the instance resides in as an instance variable so that a single flat array of components keeps track of the single source of truth. We welcome changes to the renderer or pull requests.

**Comment by franke-mc** [comment]
What would be the problem with going back to the old way of doing things in 3.x? 
I.e. 
- designate the nested `.columns[i].components` info as single source of truth
- get rid of the toplevel `.components`:
  - compute that concatenated list of components on the fly when needed, 
  - or even cache it there during use of the form in the client, but
  - never persist it.

Note that the other direction (= splitting up a single list of all components) would need to not only get the mapping to the columns right, but also the ordering of components within that column...

**Comment by travist** [comment]
We can't really get rid of toplevel "components".  Columns derives from NestedComponent which creates this and we cannot get rid of that in NestedComponent. The only thing we can do is to get rid of "columns" and make the "compoenents" be the single source of truth.

**Comment by franke-mc** [comment]
Well, you actually *did* get rid of toplevel "components" when persisting Columns in 3.x. I'm talking about [this line in Columns.js](https://github.com/formio/formio.js/blob/0fe6328b8674e79764f89b0f427d3d05d759ba50/src/components/columns/Columns.js#L39). I have verified that patching my installed Columns.js [like this](https://github.com/formio/formio.js/files/3759158/Columns.js.installed.diff.txt) indeed prevents the duplication of components for newly created Columns when the form is saved. But it is unclear to me which other side-effects this may have, or whether the commented-out parts of the patch would be necessary as well (they don't appear to work well as-is in the 4.x world), or what other parts of the code I'm missing...

**Comment by travist** [comment]
The only issue with this commit is that it is not passing this through a method which strips out all the superfluous parameters. We may be doing some work to resolve this in the soon future since a bug has come in where this problem is causing issues with using columns inside of editgrid components.

**Comment by franke-mc** [comment]
Thanks, looking forward to those changes then.

**Comment by travist** [comment]
Ok, so this did seem to be an issue... I now see what you mean when you say that "components" was getting included. The output schema should not contain "components". I was thinking that you were referring to the Columns component instance (which will include a components array instance).  I am basically doing exactly what the fix ^ does and will be included in the 4.7.0 release coming out very soon.
