### ISSUE TITLE
[BUG] FormUtils.eachComponent fails iteration on component.columns

### ISSUE THREAD

**Issue by tecnoel** [formio/formio.js#2027]
## Environment

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.6.2
- Frontend framework: Angular@8.2.5
- Renderer: angular-formio@4.2.12
- Browser: chrome
- Browser version: 77.0.3865.120

## Steps to Reproduce
1. Inside the Form Builder
2. Create a form
3. Add a column component
4. Add a TextField component inside the column component
5. Edit the submit button and change action to custom
6. Add the following code to the "Button Custom Logic"
```js
  utils.eachComponent(form.components, (component, path) => {
    console.log(component.key)
  }, true);
```
7. Save component
8. Save the form
9. In the form manager go to the "Enter Data" section
10. click submit button

## Expected behavior
  It should prints the keys of all components
  columns
  textField
  submit

## Observed behavior
  It doesn't print the keys of the components that belong to a column component
  columns
  submit

## Solution proposal
file:  formio.js/src/utils/formUtils.js 
```js
export function eachComponent(components, fn, includeAll, path, parent) {
  if (!components) return;
  path = path || '';
  components.forEach((component) => {
    ...
    
    if (!noRecurse) {
      if (hasColumns) {
        component.columns.forEach((column) =>
            //replacing
            //eachComponent(column.components, fn, includeAll, subPath(), parent ? component : null));
            //with
            eachComponent(column.components || column, fn, includeAll, subPath(), parent ? component : null);
      }

      else if (hasRows) {
        component.rows.forEach((row) => {
          if (Array.isArray(row)) {
            row.forEach((column) =>
              //maybe also replacing (I don't know, I should check)
              //eachComponent(column.components, fn, includeAll, subPath(), parent ? component : null));
              //with
              eachComponent(column.components || column, fn, includeAll, subPath(), parent ? component : null);
          }
        });
      }

      else if (hasComps) {
        eachComponent(component.components, fn, includeAll, subPath(), parent ? component : null);
      }
    }
  });
}
```

**Comment by randallknutson** [comment]
We haven't changed the logic of the eachComponent function in a very long time. What might be happening is that the eachComponent function is expecting a form definition but form.component is actually class instances which is causing it to fail. Can you use the form definition instead?

**Comment by thaisonle** [comment]
@randallknutson `eachComponent` is expecting `form.components`, passing it just the form throws an error. The same thing happens with the `flattenComponents` method.

**Comment by randallknutson** [comment]
What is the error it is throwing?

**Comment by thaisonle** [comment]
`Uncaught (in promise) TypeError: e.forEach is not a function
    at Object.g (formio.full.min.js:16)`

**Comment by agrawalankush** [comment]
I was facing the same issue, tried the recommended solution above in npm package directly and it's working as it should also no need to change in "hasrows" code. @randallknutson Can you please update library with this fix?

**Comment by wag110894** [comment]
@agrawalankush Thanks for reaching out! We will update the library with this fix and let you know once we do. For reference, the ticket number for this change is FJS-1140. 

Thank you for using Form.io!

**Comment by wag110894** [comment]
@agrawalankush, 

We have gotten feedback from our developer that was looking into this issue. Here is the information that they provided us with:

utils' eachComponent method is used for iterating through JSON schemes of components which has a specific format. So, in the Columns' JSON, each row must always be an object with the 'components' field.
But in the Columns instance, each column is just an array of components. So, for iterating through components' instances they should use everyComponent method of the Form's instance/any component's instance.
E.g.:
formInstance.everyComponent((componentInstance) => {
// Do what you want with componentInstance
return true; // In order to stop iterating just return false
});

I hope that this helps.

**Comment by SalTor** [comment]
wag11084's comment works as a solution for my problem. For our forms we use `mm/dd/yyyy` syntax for dates since that's what our audience is familiar with and then we format the payload of certain fields to use ISO date format when we submit to our backend. Had the same problem as teknoel where `Utils.eachComponent(form.components)` wasn't treating components with the same condition the same way; I just hadn't connected the dots that it was because they were in a Layout component.

Thanks all for your efforts 🚀
