### ISSUE TITLE
Contributors not getting credited appropriately?

### ISSUE THREAD

**Issue by cymen** [formio/formio.js#2036]
I enjoy contributing PRs to open source projects (and leading my own) however an important aspect of that is getting recognized as a contributor. Unfortunately, I noticed on this project, that doesn't seem to have happened when the PR I created was merged. I was surprised by that -- the PR I'm talking about is here:

https://github.com/formio/formio.js/pull/1136

Was this some kind of glitch in how things are normally done? Or is this standard procedure?

**Comment by travist** [comment]
We would never purposefully hide outside contributions. We are very proud of the community that is forming around this project so if something like this happened, then that would never be on purpose.

With that said, the issue you referenced was not a pull request... are you referring to a different one? Also, all contributions are recognized through the Github interface here https://github.com/formio/formio.js/graphs/contributors

This is also provided in our NPM package at https://raw.githubusercontent.com/formio/formio.js/master/package.json

If there is another form of recognition that you are looking for, then let us know and we will do that within reason.

**Comment by cymen** [comment]
@travist Ah, I linked to the wrong thing and then edited on github so if you read via email, it was out of date. This is what I edited to:

https://github.com/formio/formio.js/pull/1136

I was mostly just curious but figured I'd ask instead of being unsure :). No need for recognition or anything, it was a very small PR. As I mentioned, I was just curious.

**Comment by travist** [comment]
The only thing that I can think of that may have happened is that when you made the commit, you didn't use your email address associated with your Github account. I have done that in the past, and have noticed that if Github does not recognize the email associated with the commit, that it will not show your name in the contributors list. We accept PR's without checking this so that may have caused the goof. The best thing I can think of is for you to create a pull request reverting the commit and then another one re-implementing it, but make sure you use the Github email address. I am happy to work with you to ensure you get the credit you deserve. We really appreciate all contributions, no matter how "small".

**Comment by cymen** [comment]
So that would be easy to check -- we can see right here:

https://github.com/formio/formio.js/pull/1136/commits

I did use my email address. But if you click through:

https://github.com/formio/formio.js/commits?author=cymen

You get "no commits".

So what I'm more trying to point out is I think your rebase/merge methodology is flattening out contributors. I don't care about my few commits here -- we don't need to go back and fix that. I'm more thinking about how to change your process to avoid repeating the same pattern.

**Comment by randallknutson** [comment]
As Travis mentioned we would never intentionally do this. It looks like the PR was merged and then a build done which is a typically process. Seems fairly normal as we aren't rebasing anything (we never do) and just merging the pull requests with the github interface. Is there anything about that process that seems off?

**Comment by cymen** [comment]
I'd say the only thing that seems off is the lack of attribution. I'll close this but it just seems odd to me but maybe I'm missing something. Best wishes.
