### ISSUE TITLE
use custom datapicker

### ISSUE THREAD

**Issue by imohammad74** [formio/formio.js#2040]
Hello.
Can i use custom  datapicker (for jQuery) in form io?
I want use a Persian calendar  for my form.

Thanks.

**Comment by randallknutson** [comment]
You can write your own custom components and override the functionality of our standard components. This should allow you to use your own date picker. To do this, create a module and override the datetime component and change the render and attach methods. Then use your own templates to create the html the way you want it. The attach method can be used to attach the datepicker to the html elements.

Here is more documentation:
https://github.com/formio/formio.js/wiki/Modules
https://github.com/formio/formio.js/wiki/Custom-Components-API
https://github.com/formio/formio.js/wiki/Templates-API

**Comment by m-eydimorad** [comment]
Hello @imohammad74 
I need to use a Persian datepicker custom component in formio similar to your need, Did you have it or develop it? If yes, Could you please share your source code?

**Comment by travist** [comment]
This requires that you translate the Flatpickr module @ https://flatpickr.js.org/localization/.  You would need to do this in the ```customOptions``` of the datetime component like this.

```
// Not sure what the import would be here, but this gives you an idea.
import { Persian } from "flatpickr/dist/l10n/.....js";

const dateTime = FormioUtils.getComponent(form.components, 'dateTime');
dateTime.customOptions = {locale: Persian};
Formio.createForm(document.getElementById('formio'), form);
```

**Comment by ptvce** [comment]
@travist  
import { Persian } from "flatpickr/dist/l10n/.....js"   >>   this file just change the caption like name of days or months, there are many diffrence between persian calendar and the others.
for develop a custom component of persian calendar we need to change moment.js but how?  I don't know.
Could you please help?

**Comment by travist** [comment]
@ptvce this would need to be a custom component where you implement a new widget, which are found @ https://github.com/formio/formio.js/tree/master/src/widgets.

**Comment by ptvce** [comment]
@travist   could u please tell me how i can create new widget?
 in order to create a new widget i created a new widget beside input and calendar widget, then i added it in index.js that is beside other widget and then i created a custom component that extend DateTime.js component, but now i don't know how use my widget in my component?
these are my files:
[JalaliCalendarWidget.js.txt](https://github.com/formio/formio.js/files/4465975/JalaliCalendarWidget.js.txt)
[index.js.txt](https://github.com/formio/formio.js/files/4465978/index.js.txt)
[jalaliDateTime.js.txt](https://github.com/formio/formio.js/files/4465980/jalaliDateTime.js.txt)

**Comment by ptvce** [comment]
@travist   could u please tell me how i can create new widget?
 in order to create a new widget i created a new widget beside input and calendar widget, then i added it in index.js that is beside other widget and then i created a custom component that extend DateTime.js component, but now i don't know how use my widget in my component?
these are my files:
[JalaliCalendarWidget.js.txt](https://github.com/formio/formio.js/files/4465975/JalaliCalendarWidget.js.txt)
[index.js.txt](https://github.com/formio/formio.js/files/4466127/index.js.txt)

[jalaliDateTime.js.txt](https://github.com/formio/formio.js/files/4465980/jalaliDateTime.js.txt)

**Comment by travist** [comment]
Closed due to inactivity
