### ISSUE TITLE
[BUG] Simple Conditional logic change - broken live forms where multiple fields have the same key in different subcomponents

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#2068]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X ] Local deployment
    - Version: 
- Formio.js version: 4.7.7

- Browser: Chrome
- Browser version: latest

## Steps to Reproduce
1. Create attached fiddle
2. For this I am using simple conditional logic, picking the second instance of TextBox
3. When the form runs if i enter "yes" in the first box the the third box appears

## Expected behavior
When someone enters "yes" in the first textBox nothing should happen, When someone enters "yes" in the second textBox then the third box should appear

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

https://jsfiddle.net/57oudfbr/

This was working previously and is how most of our production forms are built, so there appears to have been a change that now it only links against the this instance not the correct instance of textBox.

**Comment by randallknutson** [comment]
Simple conditionals can't work with values inside of a container since it doesn't have the context. Unfortunately this previously worked due to a bug where we mixed up the contextual data and root data. We have since fixed that which solved a lot of other issues. Unfortunately it means that this isn't going to work anymore. I worked with Amin to get the same conditionals using advanced conditions. These forms will need to be updated to refer to data.containerName.fieldName for the advanced conditions.
