### ISSUE TITLE
[Feature] Edit properties in a sidebar 

### ISSUE THREAD

**Issue by midrissi** [formio/formio.js#2247]
## Environment
Please provide as many details as you can:

- Formio.js version: 4.7.8
- Frontend framework:
- Browser: Google Chrome
- Browser version:  79.0.3945.88

Is there a "simple" way to display the properties of a component in a side bar instead of a modal?

**Comment by randallknutson** [comment]
There isn't really a simple way of doing this at the moment. We've discussed changing the UI for form building some internally but haven't made any decisions yet and it probably wouldn't be coming for a while. There is one place that controls the edit form for components and currently puts it in a modal (this is in WebformBuilder.js). You could modify that section of code and put it in a div in a sidebar instead of the modal. There would be a little work involved but the code is fairly clean there so it shouldn't be too hard.

**Comment by midrissi** [comment]
Thank you @randallknutson. I will check that out
