### ISSUE TITLE
[Question] Version 4.8.0 major version ?

### ISSUE THREAD

**Issue by romain-rhieu** [formio/formio.js#2256]
Hi, I see you are really looking to stabilize version 4.8.0. Does this herald a major upgrade to your saas solution? What is your strategy for this release?

I might be interested in your saas version (entreprise) but the fact that the version is old hinders me.

Thanks

**Comment by travist** [comment]
The 4.8.0 release is going through many iterations because that will be the version where we push the Next portal @ https://next.form.io to our main Portal @ https://portal.form.io. This is a significant upgrade since it is a complete rewrite of the legacy builder and renderer built originally on AngularJS. Our hope is to get through all blocking issues and complete the release by the end of the month. At that time, we will make 4.8.0 a non-RC release.  It is not "old" either... we are constantly making updates and changes to this version.
