### ISSUE TITLE
[BUG] Form modals only work with full/builder css

### ISSUE THREAD

**Issue by paulfalgout** [formio/formio.js#2325]
## Environment
Modals can only be used if importing full.css.
Here's the related code:
https://github.com/formio/formio.js/commit/4a725f0149d678453071de25021a3ec35cef533d#diff-b8942020a339858d2d5d2af6dff622c7R215

It seems like only moving the css to a more generic place would allow for this feature to be used in more places.  It seems like it's meant to support more than just the builder and that the css was misplaced.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.8.1
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Make a form with a modal in it
2. Use any css that doesn't include the builder css
3. See the modal all the time

**Comment by randallknutson** [comment]
Hi Paul! Long time no see! You are correct about this. We really should better set the css files so the proper things are being included. For now it should be pretty easy to move the correct classes out. We should probably move that over to formio.form.css since we are using it in form rendering now and not just building.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
