### ISSUE TITLE
Property hidden + Conditional show/hide: Component always shows a second before hiding

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#2360]
When we set a component property hidden and also set a conditional show/hide the component always shows for a second before hiding.
Probably to do with execution of functions?

Kind regards,
Mario

**Comment by randallknutson** [comment]
This may have to do with the execution order. Or it could be that you are checking if the value is empty string instead of null as well. The value may start as a null and then become an empty string so it evaluates as true until the defaults get set and then goes false. Try adding an additional check in your conditional logic.

**Comment by KyooMario** [comment]
The empty string instead of null was the cause.

Thanks
Mario
