### ISSUE TITLE
Trouble using modules

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#2422]
I'm attempting to use an alternative module as documented here: https://github.com/formio/formio.js/wiki/Modules

I've so far not been able to get this to work; the rendered form still has boostrap classes in the html (e.g. `form-control` class on `<input>` elements). For what it's worth, this is in a Laravel project, but I've simplified it as much as possible; my `app.js` file and blade view are below.

I'm wondering if it would be possible for the form.io team to show a full example case of using an alternative module; perhaps with something like https://codesandbox.io/ ?

```js
import semantic from '@formio/semantic';
import { Formio } from 'formiojs';

// Formio.use(semantic) 
// I've also tried the above line outside of the window.onload bit; same result.

window.onload = function() {
    Formio.use(semantic);
    Formio.createForm(
        document.getElementById('formio'),
        'https://examples.form.io/example'
    );
};
```

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <script src="{{ mix('/js/app.js') }}"></script>
    <link rel='stylesheet' href='https://unpkg.com/formiojs@latest/dist/formio.full.min.css'>
</head>
<body>
    <div id='formio'></div>
</body>
</html>
```

**Comment by randallknutson** [comment]
What you are showing looks correct, although you should use semantic before the window onload event as you originally did it. Unfortunately online tools don't work well for demoing es6 import code since you really need a module bundler to demo it. We do have UMD builds of formiojs and semantic if you want to direct embed but that won't solve your problem.

What you could do is put a breakpoint here: https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L733 and see if you can figure out what is going wrong.

**Comment by tnorthcutt** [comment]
Thanks, @randallknutson. I got it sorted. I appreciate your response!
