### ISSUE TITLE
Dynamic values for select boxes

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#2435]
Hello

Is it possible to populate the values for select boxes dynamically? Either from a data structure from a selection box or a url?

**Comment by randallknutson** [comment]
Currently there isn't an easy way of doing this. We want to create a List component that Radio/Select/Selectboxes will derive from so that we can standardize the Select like options functionality. 

For now there are two ways of doing this:
1. Modify the form definition on load.
2. Use the datasource component to load data from a url on a change event and use Logic to change the form definition of the radio component and replace the options on the definition based on the datasource results.

**Comment by aminmc** [comment]
Thanks. Will give option 2 a go

**Comment by sabnandha** [comment]
> Thanks. Will give option 2 a go

were you able to acheive this option 2

**Comment by RadhaJ** [comment]
@randallknutson @aminmc @sabnandha did anyone achieve this?. In FormBuilder UI, is there a way to configure for select boxes to call api and populate boxes. like how we can do for Select dropdown?

**Comment by AndreLuizGarcia** [comment]
Hy @RadhaJ take a look at this two links, I hope they help you:
https://formio.github.io/formio.js/app/examples/select.html
https://help.form.io/userguide/forms/form-components#select

**Comment by rishubhjain** [comment]
Is it possible to let user free type the option if particular option is not available in the dropdown select box?

**Comment by AndreLuizGarcia** [comment]
@rishubhjain Maybe you can create an option "other" on the select and if the user selects this option you can show an input field to the user to fill with this other option.

**Comment by nedfox** [comment]
> Hy @RadhaJ take a look at this two links, I hope they help you: https://formio.github.io/formio.js/app/examples/select.html https://help.form.io/userguide/forms/form-components#select

It has been a while since you posted this. Sorry for finding this :)

Populating such select (boxes) is no problem for me, but I want to preset them with true/false.
I use Logic for this, but struggle with the LET or VAR decalarations, since I cannot get the variable into the VALUE.

This bit of code creates a select boxes, and I want to set certain checkboxes on true with Logic.

Custom Default Value (Creates the list).
if (data.selecteerGebruiker.length > 0){
  IDVault.globalList('IDM','/rest/access/entities/globalList','SCCOrganisationsActive')
    .then((data)=>{
    	instance.setFieldValue(data,'key','value');  //Pass the data that you want to set in the field as a parameter to this function. 
  });
}

Logic:
var inst = '';
if (data.selecteerGebruiker.length > 0){
IDVault.get('IDM','/rest/access/entities/list', data.selecteerGebruiker, 'user', ['sccUpassLLAllowed'])
.then((mdwrecords)=>{
  inst = mdwrecords.sccUpassLLAllowed.toString();
  console.log('Inside Logic, Inst: ' + inst);
      instance.setFieldValue(inst); // ????
      value = inst; // ????
  });
  console.log('Outside Logic, Inst: ' + inst);
  value = inst; // ALWAYS EMPTY
}

In the console, I see a value INSIDE the brackets, but the variable is EMPTY Outside the brackets:
Outside Logic, Inst:
Inside Logic, Inst: CTS

How do I populate ánd set "checked/true" in such a list? Is the VAR declaration a BUG in FormIO?

FYI: If I put manually in the last line:
value = 'CTS' it checks the box.

**Comment by nedfox** [comment]
![image](https://github.com/formio/formio.js/assets/11237641/b63ea723-1446-4a38-b06f-1b5875d9a9d5)
