### ISSUE TITLE
[BUG] Multiple Values for Number field

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#2537]
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.8.1
- Browser: Chrome
- Browser version: 80.0.3987.132

## Steps to Reproduce
1. Add number field 
2. Apply Multiple Values for this.
3. Add few different values and leave from this field

## Expected behavior
Few different values
## Observed behavior
Last focused value change on first value

Cause
![image](https://user-images.githubusercontent.com/22855299/76761526-3def3c00-6798-11ea-93ab-e1605b6518ef.png)

**Comment by wag110894** [comment]
@homashevchenko Can you upgrade to the latest version of our formio.js (4.9.0-rc.10), as we are not able to replicate this issue on the latest?

**Comment by homashevchenko** [comment]
Replicated in 4.9.0-rc.10

**Comment by wag110894** [comment]
@homashevchenko, after reviewing your test steps. We are able to replicate this issue. We have created a ticket and have added it to our backlog. We welcome a pull request and have a process to expedite. Please contact support@form.io if you are interested in expediting this issue.

We will let you know once this issue is resolved.

Thank you,

William Gay

**Comment by jhen1422** [comment]
@homashevchenko This issue has been resolved in the 4.10x branch of formio.js. Please note that the 4.10.x has not yet passed our QA testing.
