### ISSUE TITLE
Question regarding "form" vs "schema"

### ISSUE THREAD

**Issue by adamturtle** [formio/formio.js#2543]
HI,

Our application uses the form builder to create form, and stores the definition to a database. In a separate view, we load the data and use the renderer to display the form.

For now, we've been using the builder instance's 'schema' property as our form definition, which is stored to the db. However, we've run into an issue with the renderer where "dataType" is not being set on components.

I've noticed the builder instance's 'form' property appears to be similar to the 'schema' property, but will all the defaults set. In your demo (https://formio.github.io/formio.js/app/builder), I notice you display the 'schema' to the user, but render the form using 'form'.

My question is, which of these two properties should we be storing in order to render the form, and what is the difference between them?

**Comment by travist** [comment]
You should be storing ```schema```. The reason is that if you stored the full form JSON, the size of your form JSON would be huge and could overflow the MongoDB maximum size. It is for that reason that we created the ```schema``` property which is the "minified" version of the JSON. This is everything that is different than the default (which you can also get by calling ```defaultSchema``` on a component class).  If you see that a property is missing and this is something that you configured different from the default, then it would be a bug that the builder is not picking up on this difference.

**Comment by delaqch** [comment]
Why doesn't schema show minified version of Json, my code is following
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import { FormBuilder } from '@formio/react';
import JsonFormatter from 'react-json-formatter'

const root = ReactDOM.createRoot(document.getElementById('root'));
const showJson = ReactDOM.createRoot(document.getElementById('showJson'));

root.render(
    
    <FormBuilder 
    form={{
      "display": "form"
    }}
    onChange = {(schema) => console.log(schema)}
  />
);
