### ISSUE TITLE
Any Available Feature Toggles?

### ISSUE THREAD

**Issue by JRiggenbach** [formio/formio.js#2576]
My apologies if this is not the correct place to post this question, but I was curious if there was a way to toggle off some of the features with this library...don't get me wrong, I think this library is fabulous, but I have a funny feeling that my business area is going to come back to me and say that all the options are going to overwhelm our customers.  More specifically, I'd like to be able to restrict some of the options that appear when you add a component to the form (i.e. Text Field Component -> Data Tab -> Database Index).

Thanks for your time.

**Comment by christophermurphy2-allscripts** [comment]
If you are providing the builder to other clients, I can say from experience that limiting the options available is a smart choice on your part. Especially the javascript fields such as Calculated Value, since your end users might not understand how to code (or it could be a security concern). Luckily, Formio does provide you with a way to override fields. When instantiating the builder you'll probably call Formio.builder(<form-builder-element>, <form-json-or-url>). You can actually pass in a third argument, which is the options (e.g. Formio.builder(<form-builder-element>, <form-json-or-url>, <my-options>). An example options object would be something like this:

```js
{
  builder: {
    basic: false, // hide the basic group,
    myCustomGroup: {
      title: 'My Custom Group',
      default: false,
      weight: 50,
      components: {
        textfield: true, // add textfield to the custom group,
        myCustomComponent: true // add a custom component to the group
      }
    }
  }
  editForm: {
    textfield: [{
      key: 'display',
      ignore: true // hide the display tab for textfield
    }]
  }
}
```
You can get a lot fancier with this, hiding only specific fields on a tab, adding a new tab entirely, etc. The best place to learn this for me was looking at the base edit form on the 3.x branch, although I think it's been shifted around in 4.x. Hope this gives you a good starting point!

P.S. One word of caution, there do seem to be edge cases where the options don't merge properly, probably due to the way lodash's union works? In that case you can only make a new tab and/or field from scratch.
