### ISSUE TITLE
[BUG] Custom event does not update Hidden property

### ISSUE THREAD

**Issue by phucduong86** [formio/formio.js#2835]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version:  On Premise 6.9.34
- Formio.js version: 4.9.26
- Frontend framework: Javascript
- Browser: Chrome
- Browser version: 81

## Steps to Reproduce
I've created a sample form of what user ise trying to accomplish:
https://codepen.io/duongph/pen/GRpBxKJ?editors=1010
Basically there are 2 button that emit "show" and "hide" event.
The text field Logic response to the event and update Property "Hidden" on the field element to true for false.
## Expected behavior
The Input is hidden/shown on button click.
## Observed behavior
Element redraw seems to be triggered but the input does not change (show/hide)

**Comment by wag110894** [comment]
@phucduong86,

Thanks for reaching out! We are aware of this issue and it is currently on our backlog. The issue is that the Logic is not saving when Action with Component Property is set to hidden and the Set State is false. The ticket is FJS-873.

As you know, we welcome a pull request and we also have a process to expedite this issue. Please contact support@form.io if you are interested in expediting this issue.

**Comment by VennilaCity** [comment]
@wag110894 Any update this?

**Comment by wag110894** [comment]
Hello @VennilaCity, 

Thanks for reaching out. This issue is resolved on formio.js version 4.13.0.

**Comment by phucduong86** [comment]
This issue has been resolved.
