### ISSUE TITLE
[BUG] Problem in canceling file upload

### ISSUE THREAD

**Issue by mojtaba-khallash** [formio/formio.js#2837]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version: 4.10.0-rc.2
- Frontend framework: Javascript
- Browser: Chrome
- Browser version: 83

## Steps to Reproduce
1. Upload a large file
2. Try to stop uploading before finishing (The uploading file will be deleted from the UI)
3. But file continues to be uploading behind the scene, and finally it will be added to the list of uploads

![image](https://user-images.githubusercontent.com/3192517/82755837-7ee47c00-9deb-11ea-816c-0c328029e382.png)

## Expected behavior

The file should not be uploaded to the server and displayed in the UI.

## Example

The definition of form is as follows:

```json
{
    "display": "form",
    "components": [
        {
            "label": "Upload File",
            "storage": "url",
            "dir": "target/folder",
            "fileNameTemplate": "{{guid}}",
            "filePattern": "*",
            "fileMinSize": "0KB",
            "fileMaxSize": "1GB",
            "multiple": false,
            "type": "file",
            "url": "/path/to/upload",
            "input": true,
            "key": "uploadFile",
            "id": "eventfq"
        }
    ]
}
```

![error1](https://user-images.githubusercontent.com/3192517/82755562-915db600-9de9-11ea-9b47-0ba69705f541.gif)

**Comment by cmcortez** [comment]
@mojtaba-khallash Clicking on the X that is shown during upload is not a feature currently supported. This would be a new feature request if interested please contact support@form.io for an official development quote.

**Comment by dsuresh-ap** [comment]
@cmcortez I have similar behavior but the difference is that the X works and the progress dismisses. However the upload is still running (because we were not notified that the upload was canceled). I don't see anywhere in your source code where it would notify on a upload cancel.

However the behavior we want at least is how the OP described the issue, we want the X to be disabled at least where the user cannot cancel the upload. Is there anyway to get that behavior?

[Video](https://uipath-my.sharepoint.com/:v:/p/dhananjay_suresh/EXtxfG8F4i5LstP8k9vL3ysB4CfzWpuxBXGidG5_vN17nw?e=m3ATwj)

Form.IO JS : 4.12 and 4.10.5

**Comment by wag110894** [comment]
Hello @dsuresh-ap, as Carlos mentioned above, please contact support@form.io for an official development quote for this new feature.

**Comment by dsuresh-ap** [comment]
@wag110894 I wouldn't say what I want is a new feature. Our other team is using the Angular Form.IO library and the cancel button is working as we would like. (The cancel button DOESN'T work and clicking it does not perform any action). However in JS the button IS working (and dismisses the progress).

So I am wondering if there is something we are configuring incorrectly in JS that is making the cancel button functional and if there is a way to disable it.

**Comment by dsuresh-ap** [comment]
Actually @wag110894 please ignore my previous comment. The issue was that the Angular Form.IO cancel button is difficult to click on web but it functions as @cmcortez mentioned where it isn't functional. The JS Form.IO we have implemented in mobile has it easier when it comes to clicking the cancel button.

**Comment by dsuresh-ap** [comment]
I see a PR with a fix to this issue. Any ETA on when this will get merged in. https://github.com/formio/formio.js/pull/3386

**Comment by wag110894** [comment]
Hello @dsuresh-ap, 

Our CTO has provided that this will be added to our next major build, which will be the 4.13 build. We will let you know once this PR has been approved and what version of 4.13 it will be added to.

**Comment by dsuresh-ap** [comment]
This has been working. I believe it can be closed.
