### ISSUE TITLE
Jump to a Wizard Page on initialization

### ISSUE THREAD

**Issue by wymanjohnnh** [formio/formio.js#2918]
Is there an easy way when loading a Wizard Form to jump to a specific page.  For example, performing a setPage(5) to navigate to wizard page 5?

I am reloading a wizard form and need to jump to the last page that the user was on during the form initialization.

Thanks
John

**Comment by rgaidier** [comment]
Hi,
I would like the same functionality on my projects :+1:

**Comment by wag110894** [comment]
You will need to get the instance of the Form in order to navigate to the page. There are a few ways to do this.  The easiest way is to save off a global variable after the form has instantiated like so.


Formio.createForm(document.getElementById('formio'), 'https://yourproject.form.io/yourform').then(function(form) {
  // "form" is the webform instance. You can save it to the global context doing the following.
  window.form = form;
});
 

You can then do the following.

 window.form.setPage(3);
 

If you are not using "Formio.createForm" to create your form, like if you are using a framework, it is also possible to get the instance using the Formio.forms construct.

console.log(Formio.forms)

But this is an object that contains ALL instances. You will need to find the right one, or if this is the only one on your page, you could do the following.

Object.values(Formio.forms)[0].setPage(3)

I hope that this helps.

**Comment by airarrazaval** [comment]
Another option could be to use [localStorageI]() to store the current page of the user and hook into the wizard page events to update its value.  Then you could just set the page when the form is initialized.

You could have something liek this:

```js
function getPage() {
  return parseInt(localStorage.getItem('formioPage'), 10) || 0;
}

function setPage(page) {
  localStorage.setItem('formioPage', page);
}

Formio.createForm(document.getElementById('formio'), form).then((formio) => {
  formio.setPage(getPage())
  formio.on('prevPage', () => setPage(formio.page));
  formio.on('nextPage', () => setPage(formio.page));
  formio.on('wizardPageSelected', () => setPage(formio.page));
});
```

Here is a working example: https://jsfiddle.net/airarrazaval/tq1zje4d/
