### ISSUE TITLE
[BUG] "Panel Navigation Buttons" checkboxes have no effect

### ISSUE THREAD

**Issue by Baloche** [formio/formio.js#2934]
## Environment
Tested on https://formio.github.io/formio.js/app/builder with Google Chrome

## Steps to Reproduce
1. Create a Wizard
2. Open the settings of a page/panel
3. Uncheck the checkboxes under the label "Panel Navigation Buttons"

## Expected behavior
When a checkbox is unchecked, the related button should not appear in the generated form.

## Observed behavior
Unchecking the checkboxes has no effect. The buttons remain visible even if all checkboxes are unchecked.

## Explaination 
I managed to locate what may be the source of the bug in the file [Wizard.js](https://github.com/formio/formio.js/blob/master/src/Wizard.js#L556) : 

Each checkbox value is accessed with the instruction
`_.get(currentPage, 'buttonSettings.******')`,
but the actual values are in
`_.get(currentPage, 'component.buttonSettings.******')`

Replacing [the line 556](https://github.com/formio/formio.js/blob/master/src/Wizard.js#L556) by `const currentPage = this.currentPage.component;` is actually enough to fix the bug, but is it a valid fix ?

**Comment by travist** [comment]
I am looking at this and I believe you are right. This must have been left over from the 3.x renderer version and was never changed once we modified the "get currentPage" to return the page instance. Please feel free to create a pull request with your change so that you will get the attribution for this fix and we will be happy to pull it in.
