### ISSUE TITLE
Calculated values aren't checked for validation [BUG] 

### ISSUE THREAD

**Issue by nathanieltagg** [formio/formio.js#2948]
Formio.js (@latest, checked against 4.10.2) 

Computed fields apparently are not checked for validity.

Here is a fiddle: 
https://jsfiddle.net/nathanieltagg/n37hxypd/10/

The calculated value shows up, but no matter what entries are put in for 'a' and 'b', it never shows an error in the computed field.

**Comment by nathanieltagg** [comment]
At first I thought the isDirty flag should be set in checkData() if the calculated value changes.  But that doesn't work. When the independent field is changed, it triggers a change events which runs the calculation and checkData, but then something apparently triggers it to run again, and on the second checkData() pass, the value is now no longer dirty and the message clears.

I tried to put in a check so that if this.calculatedValue was defined, the isDirty flag was always set (forcing the validation), but then I run into the problem that if the form is empty, the calculatedValue is often set to NaN instead of undefined (as of my most recent submitted patch allowing non-truthy calculated values).

This reveals another problem: it is possible to have NaN as a computed value (i.e. the form divides two numeric fields, resulting in a divide-by-zero situation) which SHOULD be checked for validation (and fail such checks if the input values are bad).   But it should NOT be checked for validation if it comes about because some of the input fields are as-yet undefined.

I know I certainly don't follow the validation logic; I can't see why checkData is called more than once after a change, so I'm really just tinkering with something I don't really understand.

**Comment by airarrazaval** [comment]
I think this is the expected behavior as what you are saying is to trigger a validation error on a calculated value using values of other components.  The correct way to do it is to put the validation on the component that depends of the calculated one.

In your example you have:

* Number Component A
* Number Component B
* Number Component Result (disabled and calculated as A - B)

In this case the validation should be set in B, with the following condition:

```js
valid = input < data.a ? true : 'B should be less than A';
```

Maybe it is not so obvious using number components, but imagine you have the following:

* Text Field Component `First Name`
* Text Field Component `Last Name`
* Text Field Component `Full Name` (disabled and calculated as `First Name` + `Last Name`)

Suppose you want to have a valid `Full Name` (i.e. no numbers).   What you are proposing is that it doesn't matter if `Last Name` has invalid characters, but `Full Name` should not.  As you can see, this doesn't make sense and you should put validations on components that are editable by the user (which is the input you should be watching, not the one you are calculating).

**Comment by nathanieltagg** [comment]
That is certainly one way that calculated values should be used.  If so, it should be explicit that validation cannot be applied to calculated values!  That is not evident anywhere, and seems a major limitation.  
(In fact, this could be seen as a fairly big complaint in the Form Builder: there are multiple configuration options that are mutually contradictory, e.g. specifying both JSONLogic Validation and Custom Validation.)

In our case, we have specific cases where we are entering a fairly complex form based upon sets of measurements. The form does a sanity check on those measurements (i.e. A-B) but in this case, it is unknown if A or B is incorrect; both values are sane but the subtraction is not.  (For instance, the user might have entered them the wrong way around.)

If it's just two fields, you could get around this as you suggest.  But we are likely dealing with a lot of complex calculations, so validating the computed field is the obvious way to go.

So, there are two possible answers here:
1. Disable validation in the form builder when computed values are specified.  Give warnings on the console when the form is built.
2. Allow validation in the computed field.  My pull request seems to do this. At first I thought it was a hack to work around a deep bug - but this sounds like I'm actually implementing a new feature.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
