### ISSUE TITLE
Calculate Value going on an infinte loop when setting a value from API response with fetch

### ISSUE THREAD

**Issue by mihaiandreicut** [formio/formio.js#2966]
Hello,
I have the following situation:
on field I have Calculated Value formula:
value = myFunction(instance);

function myFunction (instance){
fetch(url,options)
.then((response) => { 
return response.json();
})
.then((responseData) => {
instance.setValue(responseData, {
noUpdateEvent: true
})
})

That cause infinte loop, alternate responseData with [object Promise]

Is there a solution for that ?
Thank you

**Comment by airarrazaval** [comment]
It is not recommended to have async functions inside custom calculated values as it will be executed multiple times.  Also, you are setting the the value to `undefined` as the function does not return any value so is redundant that declaration. 

If you need to set up a calculated value based on an async function (which may change on other component's value), then you should:

* Use an auxiliary component to use as flag (when should you update the value)
* Use an if condition inside the calculated value script in order to only execute when needed (thus avoiding multiple calls)

You could have something lake this:

---
### Calculated Value
```js
if (data.flagComponent) {
  instance.root.getComponent('flagComponent').setValue(false);
  fetch(url, options)
    .then(res => res.json())
    .then((body) => {
      instance.setValue(body);
    });
}
value = data.mycomponent;
``

Here is a working example: https://jsfiddle.net/airarrazaval/vgepn9f6/

**Comment by travist** [comment]
Thanks for the help @airarrazaval
