### ISSUE TITLE
[QUESTION] Does NoEval = true prevent JsonLogic calculateValue fields?

### ISSUE THREAD

**Issue by Gerboa** [formio/formio.js#3028]

**Comment by randallknutson** [comment]
I'm not 100% sure on this. The noeval field will prevent all custom javascript in a form from running. However, in some cases, like interpolating, we have a non-javascript workaround to still provide some functionality that is needed using string replacement instead of javascript. calculateValue MAY be one of those that has a limited functionality workaround but I don't think it is. Either way, if you set noeval to true, it will not use javascript to evaluate calculatedValue or any other fields where you can enter javascript.
