### ISSUE TITLE
[BUG] Use Camera option should be shown only when "Enable web camera" option is checked.

### ISSUE THREAD

**Issue by dev-z** [formio/formio.js#3137]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: Version v1.95.1, Renderer v4.11.1 as noted on pro.formview.io
- Frontend framework: Standalone Forms, using pro.formview.io
- Browser: Chrome
- Browser version: Version 84.0.4147.105 (Official Build) (64-bit)

## Steps to Reproduce
1. Create a File component
2. Go to "File" tab in the modal
3. Just check the "Display as image(s)" checkbox
<img width="1343" alt="Screenshot 2020-08-12 at 6 41 10 PM" src="https://user-images.githubusercontent.com/8604312/90020058-edd7bf80-dccc-11ea-898d-7f4489f590fb.png">

## Expected behavior

* The "Use Camera" option should not be there
* Images should be displayed after uploading.

<img width="625" alt="Screenshot 2020-08-12 at 6 45 51 PM" src="https://user-images.githubusercontent.com/8604312/90019540-2fb43600-dccc-11ea-938a-27cbb704edcf.png">

## Observed behavior

* "Use Camera" option is being shown even when the checkbox to enable webcam is not selected.
* Images are not being displayed. It still shows them in a tabular format (filename, size)
<img width="625" alt="Screenshot 2020-08-12 at 6 48 39 PM" src="https://user-images.githubusercontent.com/8604312/90019900-ab15e780-dccc-11ea-8f52-d467e3709293.png">

**Comment by wag110894** [comment]
Hello @dev-z, 

Thank you for reaching out! We are aware of this issue and it is currently in our Backlog. We welcome a PR and also have a process to expedite this issue if you are interested. 

Please let us know if you are interested in expediting it. For reference, the ticket number is FJS-28.

In the meantime, you can check both the Display as Camera as well as the Enable Web camera and it is working correctly.

We will let you know once this issue is resolved.

Thank you.

**Comment by dev-z** [comment]
Hi @wag110894 

The Camera does not work properly on iOS devices. On Android, I don't get the option to switch to rear camera.
I will try to go through the code and raise a PR.

**Comment by wag110894** [comment]
@dev-z 
Using your iOS device you will need to click on the browse option and then choose 'Take Camera'. Need someone to test Android.


As for the Andriod, we are seeing this issue as well. We do welcome a Pull Request in order to fix this issue. 

Thank you for taking a look at it.

Please let me know if you have any questions.

**Comment by RaphaelChua** [comment]
any updates on it?

**Comment by wag110894** [comment]
Hello @RaphaelChua, 

This item is still in our backlog. We welcome a pull request or have a process to expedite this issue if you are interested. 

We will let you know once this issue has been resolved.

Have a great day!

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
