### ISSUE TITLE
[BUG] Behaviour for disabled text area is different between .js, Angular, and React versions

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3145]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: latest
- Formio.js version: latest
- Frontend framework: js, react, angular
- Browser: chrome
- Browser version: latest

When you have a disabled text area in Angular, the render is a disabled text area.  But when you have a disabled text area in formio.js it renders as a single line div. 

I would generally expect that the text area should render as a text area but in disabled mode.

Is this a bug or expected?  If expected then how is this supposed to be used?  as you lose text area resize and line breaks when it renders as a div

**Comment by randallknutson** [comment]
This probably has to do with the different ways to disable a form and how they are handled by the different frontend libraries. Ideally they would all be the same but may have subtle differences. For example, if you set the form to disabled it will render each component in a disabled state. However, some renderers with actually switch the renderMode to "html" instead of "form" which causes an html version of the fields to be rendered which would result in the div instead of a wysiwyg. This issue is either that or the fact that angular may not be loading the wysiwyg library by default in disabled mode and so causes it not to attach properly.

**Comment by StephenOTT** [comment]
Angualr loads the text area as a disabled textarea.  But it is formio.js and React that render it as a single line div (line breaks are lost).

**Comment by wag110894** [comment]
Hello @StephenOTT. Thank you for reaching out! 

We have created a ticket for us to investigate why the disabled textareas are showing differently using Javascript, Angular, and React.  This item has been added to our backlog. We welcome a pull request or have a process to expedite as well. The ticket number is FJS-1167. Please let me know if you are interested in expediting and we can get the process started.

We will let you know once this issue has been resolved.

Thank you.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
