### ISSUE TITLE
(Question) Roadmap newer versions e.g. v5 ?

### ISSUE THREAD

**Issue by bobslee** [formio/formio.js#3187]
Hi folks,
Is there a webpage/overview with a roadmap for upcoming versions e.g. v5 ?

**Comment by randallknutson** [comment]
There currently is no public roadmap for 5.x. Here are a few of our planned features though:

- New Rules Engine (Validations, Warnings, Conditions, Variables, etc) - Completed
- Convert to typescript compiler - Completed
- Use a WASM based javascript interpreter instead of eval for sandboxed code
- Improved Translation interface and UI when building forms
- Reduce the build size
- Other cleanups and improvements

**Comment by bobslee** [comment]
Thanks!
