### ISSUE TITLE
FormioUtils: eachComponent vs flattenComponents: when to each each?

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3246]
is the only different between flatten and each is flatten returns the key-value ? Or is there a specific scenario where flatten is used?

**Comment by randallknutson** [comment]
eachComponent works a little differently since there are cases where you need to do a tree traversal as opposed to just have a list of components. Many times with nesting the api keys depend on their parent value so traversals can give you that. In addition, some components, like container and datagrid, can have duplicate components that will be lost by flattencomponents.

**Comment by StephenOTT** [comment]
So does eachComponent navigate all components regardless of their nested structures?
I am looking at something like 

https://github.com/formio/formio/blob/d0c08a27482a0ed67612616a7017b77dfa5d6738/src/resources/FormResource.js#L24

Is it designed to pickup all nested components?

**Comment by randallknutson** [comment]
Yes. It will pick up all nested components.

**Comment by StephenOTT** [comment]
Thanks
