### ISSUE TITLE
[BUG] `util.guid()`as calculate value, it will non-stop calculate 

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#3291]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] https://formio.github.io/formio.js/app/builder
- Browser: Any

## Steps to Reproduce
1. Drag and Drop a textfield
2. In calculate value, type: `value = util.guid();`
3. checked `Allow Manual Override of Calculated Value`

## Expected behavior
1. Calculate once
2. If user manual override, it will stop re-calculate

## Observed behavior
1. It will regenerate in 1 second
2. If i type the textfield, it's still  re-calculate

![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3291_0.png?raw=true)
![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3291_1.gif?raw=true)
![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3291_2.gif?raw=true)

**Comment by doublegrey** [comment]
The problem is not with the [utils.guid()](http://formio.github.io/formio.js/docs/file/src/utils/utils.js.html#lineNumber415) function. It's the way how calculated values work. Value is calculated on every tick. It is not a bug, it is expected behaviour
```js
value = Date.now();
```
![formio](https://user-images.githubusercontent.com/25150523/93999724-d812eb00-fd9e-11ea-840c-dcf27f72ca14.gif)

Have a nice day! 😄

**Comment by bleungAtGTI** [comment]
Yep,
but if i want to create random default value as id (user editable),
how to do that?

and, i have checked `Allow Manual Override of Calculated Value`,
it should stop after user override

**Comment by doublegrey** [comment]
Ok, I will show you an example of using 'Allow Manual Override of Calculated Value' property. Image you have text field with property name 'text1' and the second with 'text2'. Calculated value of text2 will be
```js
value = data['text1'];
```
Behaviour without ```Allow Manual Override of Calculated Value``` checked
![without_override](https://user-images.githubusercontent.com/25150523/94113460-93935800-fe4f-11ea-9d48-15ad861bae08.gif)

Behaviour with ```Allow Manual Override of Calculated Value``` checked
![with_override](https://user-images.githubusercontent.com/25150523/94113555-c0476f80-fe4f-11ea-9571-71c1f9199e04.gif)

**As you can see, changing text1 will cause rerender of text2, so changes will be lost. The same happens when text field with utils.guid() updates.**

JSON Schema used for demonstration
```json
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Text1",
            "tableView": true,
            "key": "text1",
            "type": "textfield",
            "input": true
        },
        {
            "label": "Text2",
            "tableView": true,
            "calculateValue": "value = data[\"text1\"];",
            "allowCalculateOverride": true,
            "key": "text2",
            "type": "textfield",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```

**Comment by bleungAtGTI** [comment]
> As you can see, changing text1 will cause rerender of text2, so changes will be lost. The same happens when text field with utils.guid() updates.

oh i see, thanks :)


but any way to generate some random id for default value?

**Comment by doublegrey** [comment]
Sure! Just move your JavaScript to ```Custom Default Value``` block:

**GUID will be generated only on field initialization**. Hope that is what you need 

![Untitled](https://user-images.githubusercontent.com/25150523/94245063-6794d700-ff22-11ea-8387-b7512cda76bc.gif)

JSON Schema used for demonstration
```json
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Text Field 1",
            "tableView": true,
            "customDefaultValue": "value = utils.guid();",
            "key": "text1",
            "type": "textfield",
            "input": true
        },
        {
            "label": "Text Field 2",
            "tableView": true,
            "calculateValue": "value = data['text1'];",
            "allowCalculateOverride": true,
            "key": "text2",
            "type": "textfield",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```
Have a nice day! 😄

**Comment by bleungAtGTI** [comment]
@doublegrey thanks a lot, this is a nice day
