### ISSUE TITLE
Server rendering is broken

### ISSUE THREAD

**Issue by joxerTMD** [formio/formio.js#361]
The what-wg polyfill you [use](https://github.com/formio/formio.js/blob/master/src/formio.js#L5) is [not](https://github.com/github/fetch/issues/184) isomorphic , so when i try to render my app on node server it fails with the following mistake: 'ReferenceError: Headers is not defined' on [this line](https://github.com/formio/formio.js/blob/master/src/formio.js#L1188). 
1) Why do you use so strange assignment in module definition? Can you remove it or make some another workaround?
2) I'm currently using Headers polyfill on my server as a workaround, but it would be great if you can fixit on your side.
Thanks! :)

**Comment by travist** [comment]
I agree this needs to be fixed. I am not sure why the ```Headers``` is assigned that way, but I assume it is done to support some legacy function. This library was built specifically for the front end, and if you want to have a similar function to server side function, then I would recommend using the https://github.com/formio/formio-service since it is built for Node.js and uses Request node module which is much better than our polyfill.

**Comment by dylanized** [comment]
I am struggling with this too, but in our scenario we don't have a username and password available - we just have a jwt token. Is there any way to pass the token into formio-service?

**Comment by travist** [comment]
Yes, just pass the key with the configuration.

```
var formio = require('formio-service')({
  key: '[YOUR API KEY]'
});

// Create a new form instance.
var form = new formio.Form('https://myapp.form.io/user');

// Iterate through all the submissions.
form.eachSubmission(function(submission) {

  // Console log the submissions.
  console.log(submission);
});
```

**Comment by travist** [comment]
Just added some docs to help with that.

https://github.com/formio/formio-service
