### ISSUE TITLE
[BUG] FormBuilder doesn't use i18n translations for custom components when another Form rendered

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#3643]
## Environment
- Hosting type
  - [] Form.io
  - [x ] Local deployment: not relevant here, issue with FormIO JS purely
- Formio.js version: 4.12.4
- Frontend framework: React, but reproducible with vanilla JS
- Browser: Google Chrome
- Browser version: Version 87.0.4280.141 (Official Build) (64-bit)

## Steps to Reproduce
1. Create an HTML page with HTML placeholder elements for a `FormBuilder` and `Form` components (we'll need to render both to reproduce the issue)
2. First, render `FormBuilder` with empty form and some custom component in language X. Provide i18n translations for language X for the custom component's title in FormBuilder's `options`
3. Just after, render `Form` component with an empty form and no i18n translations provided
4. See the issue: custom component's title is not translated

## Expected behavior
Custom component's title should always use i18n translations provided to `FormBuilder` component.

## Observed behavior
Custom component's title doesn't use i18n translations provided.

## Example
Here is a JSFiddle example to reproduce: https://jsfiddle.net/dsibinski/yq3ndxf1/22/

There are two buttons: "Render form builder only" and "Render form builder and form". If you click on "Render form builder only", then the builder is rendered correctly i.e. its custom component's title is "Losowa polska nazwa"
![image](https://user-images.githubusercontent.com/49182064/104148864-4e7e3c00-53d4-11eb-8b66-0c18c274df06.png)

However, if you click "Render form builder and form" button, the builder renders its custom component wrongly i.e. not using the translation:
![image](https://user-images.githubusercontent.com/49182064/104148882-5e961b80-53d4-11eb-93bf-082742617f0f.png)

**Comment by wag110894** [comment]
Thank you for reaching out! We are able to replicate and have added this to our backlog. For reference, the ticket number is FIO-1126.

We welcome a pull request as well as have an option to expedite this issue if you are interested. 

Please let me know if you are interested and we can get the expedited process started.

**Comment by mm-dsibinski** [comment]
Hi @wag110894 ,
thank you for answering. We'll wait until you proceed with this issue according to your dev schedule.

**Comment by wag110894** [comment]
Hello @mm-dsibinski,

Our developer that is currently looking into this issue says that this behavior is pretty normal.
When we do not pass i18next (Note that it is not the same as i18n which represents only options for i18next instance) instance inside options, then the global instance of i18next is used.

So when you first render the formBuilder with lenguage set to ‘pl' it is rendered correctly, but when you render the form where were no options (i18n property) passed to the form’s options, it sets that options to default one (where language is 'en') and since the global version of i18next was used, the default language overrides language of the global i18next instance. 

There are 2 options to fix this:

You can pass a separate instances of i18next using i18next options property

You can pass language to each created form and builder using language options property  


I hope that this helps.

Thank you.

**Comment by mm-dsibinski** [comment]
Thank for answering @wag110894 
We have applied the 2nd fix proposed by you.

For anyone else's reference, in React we set the i18next as follows:

```typescript
let transService = i18next.createInstance();
        transService.init({
            lng: languageCode,
            resources: translations as any
        })
```

there `language` is the currently desired language code and `translations` is our translations object. Then we assigned `transService` to `i18next` option of the form builder.
