### ISSUE TITLE
[BUG] beforeNext hook not fired when form is rendered with readOnly flag

### ISSUE THREAD

**Issue by AdamMYoung** [formio/formio.js#3734]
## Environment
Please provide as many details as you can: 

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.12.6
- Frontend framework: Formio.js
- Browser: Chrome
- Browser version: 86

## Steps to Reproduce
1. Add `beforeNext` and `beforePrev` hooks to a wizard
2. Navigate through the wizard using `Next` and `Previous` buttons
3. Observe events not fired on beforeNext

## Expected behavior
Events should be fired on both hooks

## Observed behavior
Events are only fired on `beforePrev`

## Example
https://jsfiddle.net/4h7rnoLx/

**Comment by wag110894** [comment]
Hello Adam, 

Thanks for providing this issue. We are able to replicate and have created a ticket and have added it to our backlog. For reference, the ticket number is FIO-1372. We welcome a pull request and also have a process to expedite. Please contact support@form.io in order to get the expediting process started.
