### ISSUE TITLE
Wrong global option object used in FormBuilder constructor

### ISSUE THREAD

**Issue by Baloche** [formio/formio.js#3754]
Hello 👋
I am trying to use a plugin providing predefined components in a custom builder group : 

```js
const plugin = {
  options: {
    builder: {
      'my-custom-group': {
        components: [/* ... */],
        title: 'My custom group'
      }
    }
  }
}

Formio.use(plugin)
```
This does not work. 

I managed to make it work by nesting my builder option in another `builder` object : 
```js
const plugin = {
  options: {
    builder: {
      builder: {
        'my-custom-group': {
          components: [/* ... */],
          title: 'My custom group'
        }
      }
    }
  }
}
```

I believe this is not the expected API. This is caused by the following line :
https://github.com/formio/formio.js/blob/b943e500d649b1d27e35237b4f13253b7d8c9b97/src/FormBuilder.js#L13

I think it should be replaced by :
```js
((Formio.options && Formio.options.builder) ? Formio.options : {})
```

I would be happy to submit a PR if someone confirm everything I just said :)

**Comment by AlexeyDavyd** [comment]
I've performed some investigation and came to a conclusion that it is an expected behavior.
Here you can take a look at the example of custom builder that uses that code: https://formio.github.io/formio.js/app/examples/custombuilder.html

This can be considered as a weird plugin behavior that might confuse users. And we might think about changing plugin logic.
But for now it works as expected.

**Comment by Baloche** [comment]
The example in the custom builder is correct :
```js
Formio.builder(document.getElementById('builder'), {}, {
  builder: { /* ... */ }
})
```

But the following line provide the value associated to the `builder` key instead of providing the global object containing the `builder` key : 
https://github.com/formio/formio.js/blob/b943e500d649b1d27e35237b4f13253b7d8c9b97/src/FormBuilder.js#L13

**Comment by travist** [comment]
We have to do this because we do not want namespace collisions between the "builder" options and the "form" options. So we take everything from ```Formio.options.builder``` and pass those as the options for the Builder. Unfortunately, there just happens to be a "builder" property in the builder options (to configure the sidebar builder), so we end up getting the ugly ```{builder: {builder: {....}}```.   Again, this is expected. If you are passing options to the builder itself, you will only see one "builder", however if you are setting the global options property, then there will be two. Works as designed.
