### ISSUE TITLE
[BUG] Formbuilder fails at  `setSelectedClasses` when two keys are decimal numbers like `6.1` and `6.2`

### ISSUE THREAD

**Issue by marcus-at-localhost** [formio/formio.js#3782]
## Environment

- Formio.js version: 4.13.0-rc.9
- Browser: latest Chrome

## Steps to Reproduce
Two checkbox components. One with a key `6.1` the other with a key `6.2` (could be also `x6.1` and `x6.2`)  fails with **Cannot read property 'toString' of undefined** in the form builder: https://github.com/formio/formio.js/blob/77575e763dd6977cef5eadcf3a57276fe7d946df/src/components/radio/Radio.js#L171

Use the following in the Sandbox:
```js
{
  "components": [
    {
      "label": "1A",
      "key": "6.6",
      "type": "selectboxes",
      "inputType": "checkbox",
      "values": [
        {
          "label": "i.O.",
          "value": "iO"
        },
        {
          "label": "n.i.O",
          "value": "nIO"
        }
      ],
      "defaultValue": {
        "iO": true,
        "nIO": false
      }
    },
    {
      "label": "1B",
      "key": "6.1",
      "type": "selectboxes",
      "inputType": "checkbox",
      "values": [
        {
          "label": "i.O.",
          "value": "iO"
        },
        {
          "label": "n.i.O",
          "value": "nIO"
        }
      ],
      "defaultValue": {
        "iO": false,
        "nIO": false
      }
    }
  ]
}
```

If I change one of the keys to something else, like `5.1`, it works.

![image](https://user-images.githubusercontent.com/1337223/108199250-01049580-711d-11eb-9623-7bfcf8c419d8.png)

**Edit** 

Looks like the dot notation of keys gets parsed. from `x6.6` to `{"x6": {"6" : "foo"}}`

**Comment by travist** [comment]
This is strange that you are using "numbers" as keys for your fields. Is there a reason you need to do this? The period in a key will always indicate a "complex" object for the data and convert it to a nested object. These components are not intended to work with complex data objects and fails, so yes this is probably a bug, but I would consider this an extreme edge case and probably won't get fixed on our end (unless a pull request is submitted from the community).

**Comment by marcus-at-localhost** [comment]
It's not me, it's the client, they thought the could simplify things.

I guess the problem is that it's not obvious that property names and value fields can't hold anything other than alphanumeric chars.
In the best case there is no reason to change them, since they are generated, but formio builder doesn't prevent me to put anything into those fields.

I guess those fields need to be sanitized in real time on keydown or onblur?! Unfortunately I'm not deep enough in the formio code. I understand if that won't be fixed. 
At least it's documented here now :)

**Comment by travist** [comment]
We should at least have a validation error show up on the "keys" if it is a numeric field. This may be a ticket that comes out of this, but it would be considered pretty low priority unless the community offers a fix as a pull request.

**Comment by jdancey-allview** [comment]
I've had this error crop up on much more normalised keys ie 'record_formInput' style of comments.  In one instance I ended up needing to programmatically add in a random character to the keys and that hack appeared to 'fix' the issue.

This function cropped up again getting errored through some conditional logic where the inputs were getting hidden.  This would then cause an error if the conditional left the input as hidden, clearing the data.  The issue was resolved with setting "clearOnHide" to false.

This seems to be triggered in particular by the form.setForm functionality.

No answers and its hard to provide better information when the behaviour is so temperamental and arbitrary in presentation but just thought I'd add some of my experiences as this is the only place where I have seen this error documented.
