### ISSUE TITLE
[BUG] Duplicated keys in DataGrid + Table

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#3973]
What i have: I have a DataGrid. In DataGrid there is a Table. Inside Tabel there is Text field.
It is latest formio4.

Open browser console and there is an error:
_[DOM] Found 2 elements with non-unique id #erxg9nu-textField: (More info: https://goo.gl/9p2vKq) <input id=​"erxg9nu-textField" value=​"aaa" spellcheck=​"true" lang=​"en" class=​"form-control" type=​"text" name=​"data[dataGrid]​[0]​[textField]​" ref=​"input">​ <input id=​"erxg9nu-textField" value spellcheck=​"true" lang=​"en" class=​"form-control" type=​"text" name=​"data[dataGrid]​[1]​[textField]​" ref=​"input">​_

Formio schema is:
```
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Data Grid",
            "reorder": false,
            "addAnotherPosition": "bottom",
            "layoutFixed": false,
            "enableRowGroups": false,
            "initEmpty": false,
            "tableView": false,
            "defaultValue": [
                {}
            ],
            "key": "dataGrid",
            "type": "datagrid",
            "input": true,
            "components": [
                {
                    "label": "Table",
                    "cellAlignment": "left",
                    "key": "table",
                    "type": "table",
                    "numRows": 1,
                    "numCols": 1,
                    "input": false,
                    "tableView": false,
                    "rows": [
                        [
                            {
                                "components": [
                                    {
                                        "label": "Text Field",
                                        "tableView": true,
                                        "key": "textField",
                                        "type": "textfield",
                                        "input": true
                                    }
                                ]
                            }
                        ]
                    ]
                }
            ]
        }
    ]
}
```

If i remove Table from between DataGrid and TextField then all looks good.

**Comment by wag110894** [comment]
Hello @krixerx, 

We are not experiencing this error when using our Sandbox.

Can you try here: https://formio.github.io/formio.js/app/sandbox
Add 6079b66f0712f223c9d40443 to the load sandbox textfield and hit Load Sandbox.

**Comment by airarrazaval** [comment]
@wag110894 I was about to create a new bug but saw this.  I will expand here:

## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: `>= 4.12.0-rc.1`
- Frontend framework: `any`
- Browser: `any`
- Browser version: `any`

## Steps to Reproduce
1. Create a form with a Data Grid
2. Insert a Columns component inside the Data Grid
3. Insert any input component inside the Columns component
4. Render the form
5. Add a second row

## Expected behavior
All components should be created with a unique HTML id.

## Observed behavior
Components inside a layout component (which in turn is inside a Data Grid, Edit Grid, etc) retain their unique id and are not updated with the parent Nested Component's row index as it should.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/9391489/125981584-d5fe6b56-2f3b-492a-80e8-a4f3871d0440.gif)

This causes the browser to trigger a warning for detecting non-unique HTML ids.

The bug was introduced in `formiojs@4.12.0-rc.1` and is still present.

## Example

https://jsfiddle.net/airarrazaval/b10pda43/

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
