### ISSUE TITLE
[BUG] FormBuilder error: Uncaught (in promise) Missing projectId

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#4048]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: N/A, custom backend
- Formio.js version: 4.13
- Frontend framework: React or vanilla JavaScript
- Browser: Google Chrome
- Browser version: Version 90.0.4430.93 (Official Build) (64-bit)

## Steps to Reproduce
1. Go to https://formio.github.io/formio.js/app/builder
2.  Open Google Chrome console

## Expected behavior
No error in the console

## Observed behavior
Error in the console:
```
builder:1 Uncaught (in promise) Missing projectId
Promise.then (async)
WebformBuilder @ WebformBuilder.js:382
create @ FormBuilder.js:82
setForm @ Form.js:253
Form @ Form.js:122
_createSuperInternal @ FormBuilder.js:50
FormBuilder @ FormBuilder.js:72
(anonymous) @ builder:137
```

We are getting the same error when rendering `FormBuilder` from FormIO 4.13 in our app.
Before 4.13 version it was ok.

## Example
Example is already present in the official FormBuilder demo page: https://formio.github.io/formio.js/app/builder

Is there any workaround for this error to not appear? Maybe some option to set, so the `projectId` is not missing anymore?

**Comment by dwaynedsouza** [comment]
I have the same issue. Any fix?

**Comment by nazmiwafiyy** [comment]
Same issue here.

**Comment by ErosII** [comment]
Mee too

**Comment by mm-dsibinski** [comment]
Hi guys, any info here? @travist , @wag110894 ?

**Comment by upexcel** [comment]
I am facing similar issue with angular.

> "angular-formio": "^4.4.5",
> "formiojs": "^4.13.2",

`zone.js:690 Unhandled Promise rejection: Missing projectId ; Zone: <root> ; Task: Promise.then ; Value: Missing projectId undefined`

can anyone help please?

**Comment by wag110894** [comment]
Apologies for the delay. 

We have created a ticket FIO-3391. We will let you know once this issue has been resolved.

**Comment by sehsanm** [comment]
Any updates regarding this bug?  It is blocker issue

**Comment by ensemblebd** [comment]
It's because formio's default renderer function doesn't pass the [options] argument, and the code that looks for it finds no 2nd argument, and thus options is empty, and thus options.base is empty, and thus projectUrl cannot be determined, so it is a blank string, and thus this error gets shoved in the console.

So yea even if you specify base, it has this logical flaw. 
`var formio = new _Formio.default(_Formio.default.projectUrl);` 
 should be 
 `var formio = new _Formio.default(_Formio.default.projectUrl, _this.options);`

It looks benign though, the system still works fine for me. It's just hard red in the console, and totally pointless.
Are you guys experiencing an actual problem with this? Or just seeing it in console like I am.

**Comment by jbarrus** [comment]
Functionality is fine, but the error logging is annoying, particularly if you have browser logs getting shipped to a logging service.

**Comment by airarrazaval** [comment]
So the issue comes from the [WebformBuilder](https://github.com/formio/formio.js/blob/0f3672cc2a94d89ae6b47b5f53dc12ecb10f74e9/src/WebformBuilder.js) class:

https://github.com/formio/formio.js/blob/0f3672cc2a94d89ae6b47b5f53dc12ecb10f74e9/src/WebformBuilder.js#L231-L243

So the builder calls `loadProject` using the current Formio instance to retrieve the project settings in search for form global settings.  This function fails if `projectId` is empty.  There are 3 ways to determine the projectId:

1. Checking that the api url has the format `.../project/:projectId/...` (explicit project id)
2. Checking if the url hostname matches the base url and getting the first path portion of the url (subdirectories)
3. Checking if hostname has a subdomain (subdomain)

https://github.com/formio/formio.js/blob/0f3672cc2a94d89ae6b47b5f53dc12ecb10f74e9/src/Formio.js#L175-L200

There is also a preliminary check to determine this as well:

https://github.com/formio/formio.js/blob/0f3672cc2a94d89ae6b47b5f53dc12ecb10f74e9/src/Formio.js#L106-L111

Of course this approach is very untrustworthy as it is made to work with the commercial setup of form.io, and unless you manually pass on the correct formio options before creating the Formio instance, it most probably fail (as an example, you may pass an IP address as path and baseURL and it will treat it as a subdomain type of project).

Here are some results for different paths (without setting options):

```js
import { Formio } from 'formiojs';

const formio = new Formio(path);
```

|path|projectId|projectUrl|formId|formUrl|
|--- |--- |--- |--- |--- |
|http://localhost|localhost|http://localhost|||
|http://localhost/project/:projectId|:projectId|http://localhost/project/:projectId|||
|http://localhost/form/:formId|localhost|http://localhost|:formId|http://localhost/form/:formId|
|http://localhost/alias|localhost|http://localhost|alias|http://localhost/alias|
|http://example.com||http://example.com|||
|http://example.com/project/:projectId|:projectId|http://example.com/project/:projectId|||
|http://example.com/form/:formId||http://example.com|:formId|http://example.com/form/:formId|
|http://example.com/alias||http://example.com|alias|http://example.com/alias|
|http://subdomain.example.com|subdomain|http://subdomain.example.com|||
|http://subdomain.example.com/project/:projectId|:projectId|http://subdomain.example.com/project/:projectId|||
|http://subdomain.example.com/form/:formId|subdomain|http://subdomain.example.com|:formId|http://subdomain.example.com/form/:formId|
|http://subdomain.example.com/alias|subdomain|http://subdomain.example.com|alias|http://subdomain.example.com/alias|
|http://127.0.0.1|127|http://127.0.0.1|||
|http://127.0.0.1/project/:projectId|:projectId|http://127.0.0.1/project/:projectId|||
|http://127.0.0.1/form/:formId|127|http://127.0.0.1|:formId|http://127.0.0.1/form/:formId|
|http://127.0.0.1/alias|127|http://127.0.0.1|alias|http://127.0.0.1/alias|

**Comment by MoraParamesh5b0** [comment]
I have same issue related to it and also getting an extra console error by just dragging to drop area as below
![image](https://user-images.githubusercontent.com/89075952/129711193-258e0235-d87e-4cfe-9fae-649a4df96482.png)
https://prnt.sc/1q45cjh
when i click action buttons of field saving like save, cancel, remove and close icon in top of window 
Below are the screenshot of errors i am getting
![image](https://user-images.githubusercontent.com/89075952/129711366-252ab869-1c99-4682-b8d5-da22e3aebcde.png)
https://prnt.sc/1q45i3u
and i am using angular 12 with below versions
"formiojs": "^4.13.5",
"angular-formio": "4.11.0",
    "@webcomponents/webcomponentsjs": "2.6.0",
    "@webcomponents/custom-elements": "1.3.0",

Help me if any thing need to change or any extra information provided

**Comment by simonv3** [comment]
In React this will actually pop up the error message pop-up that blocks the entire screen while editing, making working on a page with formio on it a bit a of a pain.

**Comment by wag110894** [comment]
We are working on making a stable release of 4.14.0. 

Change from the Branches section to the tags and you will see the latest version of 4.14.0 is rc.31.

![formio js_Changelog md at master · formio_formio j](https://user-images.githubusercontent.com/25830796/138345890-d2914588-bec8-4f63-b8dd-60be30dd1cc3.png)

**Comment by 0liver** [comment]
It is **not** happening for me in 4.14.6, though.

**Comment by bilogic** [comment]
This is part of my HTML
```HTML
<head>
    ...
    <link rel="stylesheet" href="https://cdn.form.io/formiojs/formio.full.min.css">
    <script src="https://cdn.form.io/formiojs/formio.full.min.js"></script>
</head>
<body>
    ...
    <script>
        Formio.builder(document.getElementById('builder'), {}, {})
            .then(function(builder) {
                builder.on('saveComponent', function() {
                    console.log(builder.schema);
                });
            });

        function render() {

        }
    </script>
</body>
```
![image](https://user-images.githubusercontent.com/946010/188776277-a00608eb-f592-40e8-8f10-de6eb2fc0aea.png)


1. Using the above code, form builder shows up correctly.
2. As I need the Formio code to run only after some events, I moved them into `render()`
3. But running `render()` gets the `Missing projectId` error. 
4. Any idea how I can troubleshoot?

Thank you.

**Comment by travrs629** [comment]
> In React this will actually pop up the error message pop-up that blocks the entire screen while editing, making working on a page with formio on it a bit a of a pain.

The issue apparently still happens in more recent versions, below are my related setups:

```
"@formio/contrib": "^2.0.0",
"@formio/react": "^5.3.0-rc.2",
"formiojs": "^4.15.1",
```
