### ISSUE TITLE
[BUG] textareas with inputFormat plain is rendering HTML

### ISSUE THREAD

**Issue by ddurham2** [formio/formio.js#4225]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 5996593db6dbe7bd4f2929f94cc987500769de96
- Formio.js version: 4.13.4
- Frontend framework: Angular-12
- Browser: chromium
- Browser version: v91

## Steps to Reproduce
1. create a form with a textarea with input format set to plain
2. create an object, add add some html to the text area (e.g.` <b> ... </b>`)
3. view the object with formio-js in view-only mode

## Expected behavior
With input format set to plain, I would expect to see the html tags rendered literally and not interpretted

## Observed behavior
The content of the view-only element is rendering interpreted html (e.g. `<b>` renders bold text).
This is concerning as it would possibly indicate that untrusted users who can enter data that is viewed by other users could be subject to scripting attacks.  I observed also that it will render <button> tags as buttons.  Though, I could not immediately get it to execute js.  Nonetheless, it should be a plaintext rendering.

## Example
![image](https://user-images.githubusercontent.com/4805134/126587432-286cc2db-bead-492f-a50d-ec54586e330b.png)
![image](https://user-images.githubusercontent.com/4805134/126586684-20fba57c-4747-42d7-a387-90c2b2157aa4.png)

Where I think this is occurring: 
   -> https://github.com/formio/formio.js/blob/master/src/components/textarea/TextArea.js#L67
     -> https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/well/form.ejs

Is it trying to safely render html, but stripped of potentially harmful elements?  What package is doing that?  I've known that to be risky business.  But still, plain, I would think, should render plainly.

TIA

**Comment by airarrazaval** [comment]
@ddurham2 unfortunately the client that gets downloaded by default with the formio API server (https://github.com/formio/formio-app-formio) is very outdated and uses an old version of the formio.js SDK (if I'm not wrong it is formiojs 2.x or 3.x).  This issue is not present in the latest stable version of formiojs.  In fact you can try the same in https://portal.form.io and it won't happen.

There is a bigger flaw with the `formio-app-formio` client.  You can trigger a custom javascript using the `onload` event in images (for example). 

1. Create a new form using the `formio-app-formio` client
2. Add a TextArea component with `plain` text data type and `tableView = true`
3. Create a new submission with the following value for the TextArea component

```html
<img src="https://via.placeholder.com/350x150" onload="alert('hello')" />
```

4. Go to the `View Data` section (submissions list).
5. The submission will render without sanitizing the inline javascript and the `hello` alert will be triggered

**Comment by ddurham2** [comment]
I'm using https://github.com/formio/formio.git for my API server, but I'm not serving formiojs from there.  formiojs-4.13.4 is being served up with my Angular-12 SPA app.

And unfortunately, it does seem to be behaving that way.

I tried the image hack, but it only renders the image and does not appear to execute the JS.

Is there something I need to do to prevent it from rendering HTML?

**Comment by airarrazaval** [comment]
Oh, I got it. You are absolutely right. HTML is being rendered although the component `input format` is set to Plain text.

It happens in the current form.io portal as well:

**SUBMISSION VIEW**
![image](https://user-images.githubusercontent.com/9391489/126735306-371ed7a9-326f-43b8-bca9-69529d6a3e4b.png)

**SUBMISSIONS VIEW**
![image](https://user-images.githubusercontent.com/9391489/126735353-62cd123a-5cbb-4d23-9c3f-c67698d06afb.png)

**Comment by airarrazaval** [comment]
Ok so it appears that the inputFormat property is never used in the current version of Formio.js.  I think that when formiojs shifted to templates it missed doing this check.

a fix would be to reintroduce this check in the base component class.  So the following code:

https://github.com/formio/formio.js/blob/0f3672cc2a94d89ae6b47b5f53dc12ecb10f74e9/src/components/_classes/component/Component.js#L1604-L1610

should change to:

```js
setContent(element, content) {
    if (element instanceof HTMLElement) {
      switch (this.component.inputFormat) {
        case 'plain':
          element.textContent = content
          break;
        case 'raw':
          element.innerHTML = content;
          break
        default:
          element.innerHTML = this.sanitize(content);
      }
      return true;
    }
    return false;
  }
```

**Comment by airarrazaval** [comment]
Found the problem.  The plain format has to be limited when component is disabled (readOnly or disabled = true)

```js
setContent(element, content) {
    if (element instanceof HTMLElement) {
      if (this.shouldDisabled && this.component.inputFormat === 'plain') {
        element.textContent = content;
      }
      else if (this.component.inputFormat === 'raw') {
        element.innerHTML = content;
      }
      else {
        element.innerHTML = this.sanitize(content);
      }
      return true;
    }
    return false;
  }
```

Also added the `raw` check to be able to render unsecure raw HTML (I really don't know why would anyone want this and I am still hesitant to add it).

**Comment by ddurham2** [comment]
@airarrazaval , now what do you think the chances of getting the self-hosted https://github.com/formio/formio-app-formio to use this latest version?  It would be rather good for the admins using its frontend not to be subject to such potential hijacking.

**Comment by airarrazaval** [comment]
That application is really outdated.  Updating the packages breaks a lot of stuff.  According to @travis they will eventually update the default client that comes with the open source version, but they don't have resources for the moment (see https://github.com/formio/formio-app-formio/issues/11).

I have tried to update it following the suggestions made, but unfortunately AngularJS is not my specialty and I couldn't make it work.  I think at this point it will be easier to create a new client considering there has been lots of changes since 2.32.  I do have plans to work on an open source client app but I still haven't found the time.

**Comment by WiktorKania** [comment]
Resurfacing this, it's been over a year and it's still an issue

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
