### ISSUE TITLE
[BUG] Radio button within Radio Group is deselectable

### ISSUE THREAD

**Issue by dramxx** [formio/formio.js#4681]
## Environment
- Formio.js version: 4.13.2
- Frontend framework: react
- Browser: Firefox 
- Browser version: 99.0.1

## Steps to Reproduce
1. Lets have simple Radio Group with 2 buttons: 

```js
{
  "label": "Radio",
  "optionsLabelPosition": "right",
  "inline": false,
  "tableView": false,
  "values": [
    {
      "label": "one",
      "value": "one",
      "shortcut": ""
    },
    {
      "label": "two",
      "value": "two",
      "shortcut": ""
    }
  ],
  "key": "radio",
  "type": "radio",
  "input": true
}
```

## Expected behavior
 - As this is Radio Group, deselection of Radio Button once value for group was set should not be possible.

## Observed behavior
 - When form is rendered, user can click selected value to deselect it.
 - If any value was previously saved and user deselected that value, form will on next render load with default value, not previously saved one.

**Comment by bfoese** [comment]
I would like to add that in the current state it is not possible to come up with a custom CSS style where the user will see that the radio option became unselected.

This is the initial state when opening the form:
![image](https://user-images.githubusercontent.com/1623552/168022902-69c97fa2-0f0b-457b-a9ba-d5a42ef2a885.png)

This is the markup when the user selected the first option:
![image](https://user-images.githubusercontent.com/1623552/168025904-b7329b46-9749-4dec-82f7-cf9d48e0c9b1.png)


Finally, when the user clicks the selected first option again, the native html radio input becomes visually unselected, but the attribute binding `checked="true"` is still present at the element. However, Formio internally detected that the radio group has no selected value and triggered the error message from the required field validator.
![image](https://user-images.githubusercontent.com/1623552/168026335-e190c739-e930-45e2-b44b-76c8032991ec.png)

When you want to use custom CSS instead of the native HTML radio input, you have two indicators in the markup which could be used to detect and visualize which of the radio buttons is currently selected:
- the class input.radio-selected
- the attribute input[checked=true]

Problem here is, that these indicators are also present in the markup when the user deselected the formerly selected radio option. As a workaround you could refine the CSS selector to also consider the presence of the validation error message but this workaround would only work, if the form field is marked as 'required' field cause for an optional radio button group it would not be present in the markup.

As a result, when using custom CSS the radio button is visually still selected, while the required field validation message is being shown and there is no way to fix this case.
![image](https://user-images.githubusercontent.com/1623552/168028885-2f94fc6f-9b87-46d3-90ed-cd16428a3e72.png)

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
