### ISSUE TITLE
[HELP] What is the response format?

### ISSUE THREAD

**Issue by bilogic** [formio/formio.js#4862]
I keep getting this exception in console log

![image](https://user-images.githubusercontent.com/946010/190608522-13fe1941-af43-4125-b909-c004e171c23c.png)

# Part 1
https://github.com/formio/formio.js/blob/040e5901d977083d08b540ce27d772bcc704fea0/src/Webform.js#L1632-L1638
# Part 2
https://github.com/formio/formio.js/blob/040e5901d977083d08b540ce27d772bcc704fea0/src/Webform.js#L1246-L1248

If there was an issue with the submission in part 1, what kind of JSON format should be returned?
Because line 1637 calls into line 1247 and results in an exception.

**Comment by travist** [comment]
It is very possible that this is a bug within the showErrors function where it expects to receive a list of errors in the form.io error format which should include an array of "messages" attached to each error object. Looking at the code, I believe that you may be able to make to cooperate by changing the code to look like the following.

```
this.showErrors({messages: [`${e.statusText ? e.statusText : ''} ${e.status ? e.status : e}`]});
```

I have not tried this myself, so let me know if this does not work. Ultimately we may need to make a change to the showErrors function so that it can handle multiple formats.

**Comment by bilogic** [comment]
thanks, let me try. I have another PR, possible to accept? https://github.com/formio/formio.js/pull/4854

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
