### ISSUE TITLE
SaveDraft is not working for me

### ISSUE THREAD

**Issue by DonAmit197** [formio/formio.js#4919]
My requirement is when I click the Save button the user input will save into a draft and as in Form IO under "Use" behavior user will be redirected to a page to view the draft mode. Again on clicking the Edit button there, the user can start editing the rest of the fields.

I tried to integrate following the documentation, but not working for me:
```
Formio.createForm(document.querySelector("#<%=tools.getParamValue("formIOID") %>"), <%= jsonText %>, {saveDraft: true}).then(function(form){
 getNextPageResponse(form);
 saveSubmit(form);
       
});
```
I am also instantiating the method to `window.location` inside the` submit `event, still no luck.

Any help is highly appreciated.

**Comment by edwinanciani** [comment]
Try setting the submission.state property to "draft" before submit. 
`form.submission.state = 'draft';`

**Comment by DonAmit197** [comment]
Thanks, @edwinanciani for your comment. I'll look into it.

**Comment by phucduong86** [comment]
Hi,

I'm also having no luck with getting this feature working.
We host an on premise enterprise environment (Portal version Application: 7.0.40, Renderer: 4.11.3)

I follow the documentation here: https://formio.github.io/formio.js/app/examples/savedraft.html

And created this form: https://codepen.io/duongph/pen/VwYZvaV
I verified the Formio.setUser function worked:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/21692768/203426934-25a5016c-00b6-49b2-917e-a43c7a51e539.png">

When the  "Save as draft" button is clicked, the draft submission is successfully submitted, however there seems to be several issues:
- Spin icon does not stop on the Save as Draft button
- The "owner" is not set on the submission
- When returning to the form (refresh or open a new browser tab) the data is not restored. If I check console the error shows "Cannot restore draft because there is no formio instance."
<img width="958" alt="image" src="https://user-images.githubusercontent.com/21692768/203427180-2fcfcab0-e43d-41e7-9aee-3fed63795197.png">

**Comment by DonAmit197** [comment]
I modified the script and it worked for me. 
Form Io has a method ` if(component.component.key ==="")` with which we can trigger any component. Through it, I found the Save button component and initiated my custom function to save the form data and it's working perfectly for me.

**Comment by apasashkov** [comment]
@phucduong86 have you actually solved this issue? I have the same behavior.

**Comment by vineelaampili** [comment]
hi  @DonAmit197  can you send a piece of code which has  if(component.component.key ==="") i want to know the way of using?

**Comment by DonAmit197** [comment]
You can only use what you are after in form.everyComponent method where component is a parameter.

**Comment by phucduong86** [comment]
> @phucduong86 have you actually solved this issue? I have the same behavior.

Hi, unfortunately no we are shelving this work item for now.
