### ISSUE TITLE
[BUG]  RenderMode html is not working

### ISSUE THREAD

**Issue by DonAmit197** [formio/formio.js#4978]
Hi,
I can see `renderMode:'html'` is not working.
```
Formio.createForm(document.querySelector("#formIO"), reviewFormData,{
   renderMode:'html',
     })
```
I think there is a BUG yet. Please share some thoughts.

**Comment by brendanbond** [comment]
Hi @DonAmit197 I believe the `renderMode: 'html'` option allows you to view *submissions* as HTML documents rather than as forms. I've whipped up a quick example JSFiddle for you here: https://jsfiddle.net/brendanbond/Lk4qm9xt/3/

I'm going to close this issue, but please let us know if you have any additional questions
