### ISSUE TITLE
[Question] 'allow popups' permission is not set

### ISSUE THREAD

**Issue by robertoAPI** [formio/formio.js#5056]
## Environment
Please provide as many details as you can:
I have uploaded a pdf to Formio and added an HTML element to the pdf for a user to click on. When the HTML element is click, I recieve an error: "Blocked opening 'https://pdf_file.pdf' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set."

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 1.0.0
- Frontend framework: AngularJS
- Browser: Google Chrome
- Browser version: 109.0.5414.119 

## Steps to Reproduce
1. 
2. 
3. 

## Expected behavior
My goal is to have a new tab open up when a user clicks on the HTML element.

## Observed behavior
I receive the error stated above.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

**Comment by brendanbond** [comment]
Hi @robertoAPI, thanks for filing this issue. iFrames are occasionally a tricky business, and we don't pass the sandbox attribute [when we create the iFrame element](https://github.com/formio/formio.js/blob/29e5e749d2ac6a0eff9fd77839ba186525e518f2/src/PDF.js#L109) because we're assuming that you just want to view a PDF and want strict sandboxing. It may be a good idea to allow sandbox permissions under certain circumstances, but it probably deserves some thought and I don't think it's going to be a high priority for us. That said, if you wanted to tackle this, PRs are always welcome!
