### ISSUE TITLE
How to know when data loaded completely?

### ISSUE THREAD

**Issue by opcodewriter** [formio/formio.js#5085]
I have a `select` component with a data url which returns items a bit slow.
Is there a way to know when the form has been completely loaded?

I tried with 'initialized' even without luck:
```
form = await Formio.createForm(...);

form.on('initialized', () => { });
```

**Comment by Sefriol** [comment]
I think the problem currently is that form is initialized with empty submission. So the form will be always initialized before the real data is loaded. Therefore the it's not really reliable event to keep track on. I think this was fixed in one of the release candicates. Maybe 4.15?

You can also try to wait for submissionReady promise. After you have set the submission. https://github.com/formio/formio.js/blob/d92a6752c1d9f1ccbf632565ab9f258b96b25df7/src/Webform.js#L244

But it depends on your implementation. Currently there isn't very reliable way to do this.

**Comment by opcodewriter** [comment]
@Sefriol Thank you for your answer.

Makes me wonder how does everyone which uses FormIo makes sure the data is completely loaded before letting the user interact with the form?

**Comment by lane-formio** [comment]
<div>Agent Lane Doughtie linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/48273">48273</a> for this issue.</div><br/>

**Comment by brendanbond** [comment]
@opcodewriter did you try using the submissionReady promise? that's what it's for

also, I believe that Select components that fetch from URL are lazily loaded by default, so rendering the submission and fetching data from a 3rd party API are not always as interrelated as you might think.
