### ISSUE TITLE
File Upload as a URL

### ISSUE THREAD

**Issue by DonAmit197** [formio/formio.js#5099]
Hi,
We are integrating formio renderer in a BPM tool (Pega), and in our server node js is not installed. 
Our requirement on the file component is to work with the URL instead of Base64.

Since we are not using node js, can anyone help me with an example on how can I handle this file component based on URL?

**Comment by GMacAussie** [comment]
G'day DonAmit197,

We wrote our own URL storage provider, but I am not sure if that is what you are looking for. In essence, the URL storage provider calls our web server APIs to do the get, put and delete. Some finer points:

1. Obviously you must take care of authentication. By implementing the above HTTP verbs you get to do that;
2. For us, since the creation of the upload and the form (draft) save happens async, it is possible (without correct handling) to have the user delete a file upload and not save the form, meaning that the form can no longer get the blob which caused downstream issues for us.
We put in place an immediate (and I mean immediate) draft save after an upload delete but users STILL were able to close the tab/browser/device before the draft save took effect (< 1 second gap most times). We addressed this by removing the upload file data entry from the draft form on the server during the delete blob itself and gating the draft save until the upload delete completes (to prevent race condition).

We looked at the Formio URL provider for details:

```src\providers\storage\url.js```

You would need to implement the `uploadFile`, `deleteFile` and `downloadFile` functions. We also monkey patched the `FileComponent.prototype.getFile` function to also download via our services to allow authentication handling (we use both token-based and HTTP cookie based authentication so it is a bit more complicated).

Cheers,
Graham

**Comment by DonAmit197** [comment]
Thanks @GMacAussie , for sharing this.
It will definitely help me, but my case is that I'm unable to use node js as the js files we work on runtime in the server, but will definitely look into your option.

**Comment by ZenMasterJacob20011** [comment]
To communicate with file storage servers we use ng-file-upload library. The README of this library has examples on how to setup compatible servers for custom URL file storage in a couple different server side languages (https://github.com/danialfarid/ng-file-upload#server). Once you have a server set up to handle file storage you can then create a form with a file component and point the URL to the appropriate endpoint of your custom server
```
Formio.createForm(document.getElementById('formio'), {
  components: [{
    "label": "Upload",
    "tableView": false,
    "storage": "url",
    "webcam": false,
    "capture": false,
    "fileTypes": [{
      "label": "",
      "value": ""
    }],
    "validateWhenHidden": false,
    "key": "file",
    "type": "file",
    "input": true,
    "url": "http://yourCustomServerEndpoint"
  }]
});
```
