### ISSUE TITLE
schema.json schema for formio format?

### ISSUE THREAD

**Issue by tacman** [formio/formio.js#5142]
I'm new to nosql, and struggling with how to define a nosql data structure.  It occurs to me that there's huge overlap between the formio json and the data I'm modeling.  Obviously, they're not the same, but I'm wondering if there's a way to reuse the formio structure with something like schema.json

That is, it has label, type, min, max, description, options, etc.  

I need something to describe our data that's not in a relational database, and one candidate is just using formio to build not just the form but that data description as well.  Has this been done before?  Or any advise?

Thanks.

**Comment by brendanbond** [comment]
> I need something to describe our data that's not in a relational database, and one candidate is just using formio to build not just the form but that data description as well. Has this been done before?

This is the key concept behind the [Form.io platform](https://form.io) - that the singular connective tissue between your data and your application can abstracted into a singular interface (forms). Need to model data for your application? Create a form (that creates an RESTful API automatically). Need to interact with that data with additional constraints? Create a form. Need non-technical folks to be able to modify data structures as well as application level concerns without knowing how to code? Easy, because they're just forms and can be modified via the form builder.

**Comment by tacman** [comment]
Is there a way to create a form via a PHP api?  That is, I have a table description and I want to create the same JSON form I'd create going through the user interface.

Obviously, I can figure out by looking at what's created, but if it's described (like maybe with something from schema.org), maybe that would help with at least validation.

Or am I thinking about this wrong?

**Comment by lane-formio** [comment]
<div>Agent Jeriah Henley linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/48551">48551</a> for this issue.</div><br/>

**Comment by brendanbond** [comment]
> Is there a way to create a form via a PHP api?

Yep! It's just JSON being passed around.

> Obviously, I can figure out by looking at what's created, but if it's described (like maybe with something from schema.org), maybe that would help with at least validation.


Something like schema.org to document the JSON schema is on the roadmap, but the form definitions are so dynamic that for now just looking at what's created is the way forward. I'm going to close this issue for now, feel free to let me know if you have any more questions.
