### ISSUE TITLE
Disable calculations and logic

### ISSUE THREAD

**Issue by AnthonyPhan** [formio/formio.js#5179]
Hi,

Is there a way to disable calculated values and logic?
We have a screen that renders submitted forms with `readOnly: true`. However, I noticed that the calculated fields and logic still run which can overwrite values that are loaded by in by the submission json.

**Comment by travist** [comment]
You can turn off the Evaluator with the "noeval" flag.

```
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example', {
  noeval: true,
  readOnly: true
});
```

**Comment by jmast02** [comment]
@travist I've currently upgraded to Formio 3.1.0 from Formio 2.5.0 and in 2.5.0 when using the calculateValue field and rendering a submission in `readOnly: true` mode, the calculateValue field did not re-calculate, and showed the correct submission data for that given text field. This was also when using formiojs@4.14.8.

Now when upgrading and using Formio 3.1.0 along with formiojs@4.15.0, and viewing a submission in a `readOnly: true` mode, the calculateValue re-calculates. I always want the submission data to render, rather than re-calculate for every given user viewing the submission.

I tried the `noeval: true` method, but doesn't seem to be working in my case.

When viewing a submission in readOnly mode, is the form submission expected to re-calculate when a field has a calculateValue defined?

**Comment by jmast02** [comment]
@AnthonyPhan Hey Anthony, were you able to successfully get this working as you desired? I am looking into the same exact thing.
