### ISSUE TITLE
Adding video URL in Content Component not rendering.

### ISSUE THREAD

**Issue by TusharGoel14** [formio/formio.js#5180]
In Content Component under Layout, adding video url not rendering the same in form builder and render.

![AddingVideoContent-min](https://github.com/formio/formio.js/assets/84577843/cac5897e-eb40-439f-8332-6104a4af9ad4)

**Comment by travist** [comment]
I am certain this is caused by the sanitization process of our renderer is stripping out the video content. This can be changed by adding flags to the renderer to allow the video embed codes to the dompurify library.  This is done by passing the following as options to the renderer.

```
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/myform', {
  sanitizeConfig: {
     addTags: ['object', 'iframe']
  }
});
```

There are several options, and they are passed to dompurify here.  https://github.com/formio/formio.js/blob/master/src/utils/utils.js#L1294

Here are the docs for dompurify on how the html can be allowed.

https://github.com/cure53/DOMPurify
