### ISSUE TITLE
Why is there scroll bar for `Data Grid` and cuts off `Select`?

### ISSUE THREAD

**Issue by bilogic** [formio/formio.js#5216]
![image](https://github.com/formio/formio/assets/946010/4250ad54-4a9a-4fc5-96f0-febc70d6d256)
![image](https://github.com/formio/formio/assets/946010/4121eff8-4434-4d61-9b4f-c68e2efd140b)

Hi,

1. why does the `data grid` component have a scroll bar?
2. And why does it cut off the `select` in such an ugly manner?

**Comment by chrisdecrypted** [comment]
I'm not sure why this decision was made, but here's how I was able to override this behavior with CSS:

.formio-component-datagrid {
  overflow: visible !important;
  height: auto !important;
}

**Comment by travist** [comment]
From what I can gather, it seems like we added an overflow-x property to "auto" so that the datagrid could scroll side to side if it does not fit in the width of the screen. This must also "inform" the overflow-y to also be set to auto. I am submitting a change, that may fix it, but I am not sure if it will.  I will push this to our example application soon and we can try it out.

https://github.com/formio/formio.js/pull/5299

**Comment by ZenMasterJacob20011** [comment]
Thank you for taking the time to report this issue. This issue has been resolved.
