### ISSUE TITLE
CkEditor : For text area selecting ckeditor and toggling multiple values form is getting hanged.

### ISSUE THREAD

**Issue by Lakshmiprabhak** [formio/formio.js#5477]
## Environment:
 For text area selecting ckeditor and toggling multiple values form is getting hangged.

**Hosting Type** : https://formio.github.io/formio.js/app/sandbox.html
**Formio js Version** : 4.x Latest (Default)

## Expected Behavior:
 For text area selecting ckeditor and toggling multiple values form should not get hannged.

## STEPS-TO-REPRODUCE:
1)Drag and drop  Textarea component 
2) select editor as a ckeditor in display
3)Goto data tab and check in for multiple values
4)Then un check the multiple values
5)Observed form getting hannged 

## Attached GIF for reference:

https://github.com/formio/formio.js/assets/81677482/265e7232-f716-4383-a44a-0ea57b8ffc3e

**Comment by Sidiro23** [comment]
Thank you for reporting this issue. I am able to reproduce and have logged a ticket for the backlog. We are always willing to review any contributions to resolve this issue from the open source community.

For internal reference: https://formio.atlassian.net/browse/FIO-8123

**Comment by heather-formio** [comment]
To enable this use case, please use an edit grid or data grid with a text area with CKEditor enabled, instead of using a Text Area with the multiple values flag checked. We welcome a PR for this behavior change if you would like to contribute, but it will not be prioritized as there are other ways to accomplish the desired behaviors. I am closing this ticket, thank you for your contributions!
