### ISSUE TITLE
Number component template: type="number", instead of type="text"

### ISSUE THREAD

**Issue by bobslee** [formio/formio.js#5699]
Why does the template of the Number component have a `type="text"` instead of `type="number"` ?

With `type="number"` there're some additional features possible (like step, shown in the screenshot).

Documentation `<input type="number">`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

![image](https://github.com/user-attachments/assets/7a873d9f-d315-450c-b32c-2d052fdfc224)

Unfortunately it's not possible to override the `type` attribute from the Layout HTML Attributes, see screenshot below.
The `<input type="text">` remains.

![image](https://github.com/user-attachments/assets/d5eb848e-7358-4772-9b4a-b3d8b95171c5)

**Comment by lane-formio** [comment]
<div>Agent Tatsiana Ivashevich linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/51667">51667</a> for this issue.</div><br/>

**Comment by travist** [comment]
There are 2 main reasons why we did not use "type" number for the input type.

1. Browsers treat this (or at least used to) differently from each other. There was a time when the "number" type would cause irregularities in behavior on how the number component worked. This may no longer be a problem since most browsers today are pretty consistent with regards to the different types of inputs.  There was also major problems with Internationalization where it would not work across all browsers the different kinds of Number input formats for all internationalizations. Again, this may not be a problem anymore, but it was a big problem when we originally designed the renderer.
2. Input Masks are not compatible with "number" type inputs. By using "number" we would actually lose some features that we achieve with the Input Masks.  For example, if you need a Number component that hides the input (using "*" chars) then we would need to change the type dynamically based on what features in the Number component you are using. 

For us, it is WAY easier to just make a Text input force the input chars to numbers than the other way around, so we chose to use "text" for the input of numbers.

**Comment by bobslee** [comment]
Thanks for the detailed explanation ! 
Those are some valid points.
