### ISSUE TITLE
Multiple issues with select component including on demo website

### ISSUE THREAD

**Issue by dontfeedthecode** [formio/formio.js#627]
I've found two major issues with the select component, these can both be replicated on https://formio.github.io/formio.js/app/builder as well as on the master branch in Chrome Version 68.0.3440.106 (Official Build) (64-bit).

1. If you add a few static values to the select list and disable static search, the select list will remain empty and display no options when the form is rendered. The options exist in the DOM when you inspect the drop down, they just don't display.
2. If you uncheck the Enable Static Search checkbox, save the component and edit it again, the checkbox will revert back to being checked again.

**Comment by jhen1422** [comment]
Hello Tim,
 
Jeriah here from the Form.io support team. 

Thank you for reaching out to us and bringing these issues to our attention. 
 
We were able to replicate the issues you described. We have a planning meeting every week where we go through any outstanding issues and prioritize issues based on our platform needs. We do offer the option to prioritize issues for an expedite fee. Please let me know if you’re interested and I can send you additional information for expediting. Otherwise, we will add these items to our backlog and promptly notify you when these issues get fixed. 
 
For your reference, the ticket number for these issues are 
FOR-1646
FOR-1647

**Comment by dontfeedthecode** [comment]
Hi Jeriah, do we need to pay an expedite fee if we're already paying for a Team Pro account? Username is SpatialMedia. Cheers.

**Comment by wag110894** [comment]
Hello Tim, 

Thank you for your patience while we were working on theses two issues for you. These issues have been resolved in our latest version of our Core Renderer (3.7.0).

Please let me know if you have any further questions or concerns.

Thanks!
