### ISSUE TITLE
First value of radio button always empties after adding another

### ISSUE THREAD

**Issue by dontfeedthecode** [formio/formio.js#664]
Problem can be replicated on the form builder on the documentation website by creating a radio button field, entering a label and value for the first radio button and clicking "Add Another". You end up with two empty radio buttons.

https://formio.github.io/formio.js/app/builder

**Comment by wag110894** [comment]
Hello Tim, 

This is William with the form.io support team. Thanks for reaching out! We have confirmed that this is an issue. For your reference, the ticket number for upon the initial load of the form builder, when you add a radio component, create a 1 value, and add a new value, the Label and Value reset and are blank is FOR-1693. 
We will notify you once this issue is resolved. 
Please let me know if you have any further questions and concerns. 

Thanks,

**Comment by jhen1422** [comment]
This issue has been resolved on the latest version of formio.js
