### ISSUE TITLE
Cannot manually specify value for radio buttons

### ISSUE THREAD

**Issue by dontfeedthecode** [formio/formio.js#665]
Problem can be replicated on the form builder on the documentation website by adding a radio button to the form, entering a label for the first value and trying to alter the auto-generated camel cased value. As soon as the value field loses focus it automatically generates its value based on the label again.

https://formio.github.io/formio.js/app/builder

**Comment by wag110894** [comment]
Hello Tim, 

This is William with the form.io support team. Thanks for reaching out! We have confirmed that this is an issue. For your reference, the ticket number for being unable to modify the 'value' of a radio component value is FOR-1692. 

We will notify you once this issue is resolved. 
Please let me know if you have any further questions and concerns. 

Thanks,

William Gay
Form.io Developer Support

**Comment by dontfeedthecode** [comment]
@wag110894 Just checking to see if any progress has been made on this internally?

**Comment by wag110894** [comment]
Hello,  
 
Thank you for your patience regarding issue FOR-1692 (Unable to modify the 'value' of a radio and select boxes component values.)
 
You are now able to manually specify the value for radio buttons as well as select boxes. 
 
Please let me know if you have any further questions or concerns.
 
Thanks,

**Comment by jhen1422** [comment]
This issue has been resolved with the latest version of formio.js
