### ISSUE TITLE
Global "data" variable changed in EditGrid Component

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#700]
Currently when accessing the data variable inside a custom validation (JavaScript) in a component inside an editgrid, the global `data` variable is being replaced by the `row` variable after the first validation check.

The first time the validation script is executed, the `data` variable is correct.  If you set a value for the component and trigger the validation script again, the `data` variable is changed with the row variable, thus unable to access the global `data` variable to perform validations.

You may find examples replicating this issue here: 

* Example Form: https://mxutsqrnrusfanc.form.io/issue/700
* CodePen: https://codepen.io/airarrazaval/pen/QZbzWe

**Comment by wag110894** [comment]
Hello Alfredo,

This is William with the Form.io support team.

Thanks for reaching out! 

We have created a ticket and have tagged you on it. For reference, the ticket number is FOR-1747. We have assigned this to one of our developers. We will notify you once this issue is resolved. 

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by travist** [comment]
I believe this is resolved by this pull request. https://github.com/formio/formio.js/pull/709

**Comment by wag110894** [comment]
Hello Alfredo,

Just confirming that the pull request above fixed this issue that you were having.

Please let me know if you have any further questions or concerns.
Thanks,
William Gay
Form.io Developer Support

**Comment by airarrazaval** [comment]
I confirm it is fixed. Thanks.
