### ISSUE TITLE
Multiple validation error messages

### ISSUE THREAD

**Issue by mbahr777** [formio/formio.js#726]
Using 3.6.6. fomio.js

The last page of a wizard form, when it has a required field that is left blank, will show 4 validation messages:

Please fix the following errors before submitting.
Number Field is required
Number Field is required
Number Field is required
Number Field is required

A sample form where the error message is attached.

[components.json.txt](https://github.com/formio/formio.js/files/2469184/components.json.txt)

**Comment by wag110894** [comment]
Hello Michael,
 
This is William with the Form.io support team.
 
Thanks for reaching out! 
We have created a ticket and have tagged you on this issue. For reference, the ticket number is FOR-1779. We will let you know when this issue is resolved. 
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by wag110894** [comment]
Hello Michael,

This is William with the Form.io support team. 

We reviewed this in planning and although it was not determined to be a high priority for the platform, we have added it to our backlog.

If you need this resolved sooner rather an later, we do offer a chance to expedite this issue. Our development team has estimated this issue at 3 hours.  Please let me know if you’re interested and I can send you a formal quote.

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by jhen1422** [comment]
This item has been resolved on the latest 4x renderer.
