### ISSUE TITLE
When value gets deleted, component value change does not get detected

### ISSUE THREAD

**Issue by marguslaak** [formio/formio.js#728]
https://github.com/formio/formio.js/blob/6de1a3ffdc5ced9669b696b69911010b8d79ef8f/src/components/base/Base.js#L2028

At the line above, when a components value gets deleted (for example using backspace on a text field with one character), then newValue becomes undefined. Even if the  this.dataValue is something other than undefined, then the change is not propagated to all the required components. Events are not triggered as well.

**Comment by wag110894** [comment]
Hello Margus,

We have created a ticket and have tagged you on this. For reference, the ticket number is FOR-1784. We will notify you once this issue is resolved. 

We would love to connect hear about your project and see how we can help.   
We also have support packages available for training, support or development services if you are interested! 

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by marguslaak** [comment]
To be honest, then I do have a problem. I am trying to make 9 formio forms work nicely on a single page using one submission using vuejs. The idea is, that when you change a number or click some checkboxes on one form, then the other forms reacts to it by changing looks or calculating some hidden values. It used to work out of the box with older version of ngFormio, but now the forms don't seem to distribute the submission data properly between themselves. Is this approach still supported?

**Comment by wag110894** [comment]
Hello Margus,
 
Could you please send your sample forms and a detailed step-by-step so that we can reproduce this issue?
 
Thanks,
William Gay
Form.io Support team
