### ISSUE TITLE
Can't modify searchEnabled param for select component.

### ISSUE THREAD

**Issue by ivanyukio** [formio/formio.js#754]
Hello,

I have a simple select on a form, I don't wan't my select to have the `Type to search` box on the top, or any search whatsoever since my select will only have a few items.

I see that the [select component is set up to pass this property](https://github.com/formio/formio.js/blob/master/src/components/select/Select.js#L493), but I couldn't figure out how to do it through the edit page. I tried adding it to the `Custom Properties` as you can see below but that didn't set the `searchEnabled` from my select to `false`.

I'm also attaching a capture of my current `Display` section for reference, all of the other menus have the default options still, and the data is set up with only some label/values, not external.

Unsuccessful custom property
![image](https://user-images.githubusercontent.com/8966395/47575749-0c779580-d943-11e8-9e88-19283a70afc0.png)

Current display settings
![image](https://user-images.githubusercontent.com/8966395/47575714-fb2e8900-d942-11e8-87b1-864283f20da9.png)

Thanks

**Comment by wag110894** [comment]
Hello Ivan,
 
Thanks for reaching out! 
 
We appreciate your feedback and have put this on our backlog. We have tagged you to this existing issue. For reference, the ticket number is FOR-1555. We will notify you once this issue is resolved. 
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by jhen1422** [comment]
This should be resolved in our 4x renderer
