### ISSUE TITLE
is there a way to make multiple values component sortable ?

### ISSUE THREAD

**Issue by kran** [formio/formio.js#772]
Like "sortable" plugin in jQuery UI.

I notice that multiple values components generated by formio have names like "fld[0][a]", so just change the DOM order is not enough for generating the right ordered json array. 

is there an easy way to work around this ?

**Comment by wag110894** [comment]
Hello,
 
We do not currently have this functionality built into our renderer. 
However, you can listen for change events in the form and modify the submission object to manually sort them. Here is a similar example: http://formio.github.io/formio.js/app/examples/externalload.html 
Instead of loading data, you can get the values array,sort and rest on the submission object. Please note that this will reflect in the form if you set the submission again.
 
Please let me know if you have any further questions or  concerns.
 
Thanks,
William Gay 
Form.io Developer Support

**Comment by kran** [comment]
see it, thank you.
