### ISSUE TITLE
Multiple calls of on Submit handler

### ISSUE THREAD

**Issue by pgupta-infoobjects** [formio/formio.js#781]
Hi, I passed onSubmit handler to form component to call an external API. When submitted the form, the submit handler is called multiple times (2 times).

**Comment by wag110894** [comment]
Hello Puneet,

This is William with the Form.io support team. Thanks for the feedback!

We are able to replicate this issue on our end. We have created a ticket (FOR-1848) and have tagged you on it. We will let you know when the issue is resolved. 

Please let me know if you have any further questions or concerns.

Thanks,

**Comment by wag110894** [comment]
Hello Puneet, 

Thanks for reaching out! 

After discussion with the team, we have added this to our backlog. It may be some time before this item addressed but we will gladly accept a pull request if you would like to fix it. Alternatively, we offer support packages if you are interested in Form.io addressing this issue quickly.

Thanks!

**Comment by jhen1422** [comment]
@pgupta-infoobjects 
This should be resolved on our 4x renderer. If the issue persists please open a new issue.

Thanks!
