### ISSUE TITLE
Translation of tooltips and HTML components not working

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#815]
We are trying to translate Tooltips and HTML elements but that this is not implemented.

Could you please let us know how to translate these elements?

Best

**Comment by randallknutson** [comment]
The way we do translations is with the t function here: https://github.com/formio/formio.js/blob/master/src/Component.js#L340-L348

If you can find the place in the code where html elements and tooltips are being rendered you can wrap them in a t function to translate the items.

**Comment by travist** [comment]
Translating HTML would be difficult since you would need to provide the markup within the translation (which is probably why it wasn't implemented). You would need to pass the following line through the ```this.t()``` method to translate.

https://github.com/formio/formio.js/blob/master/src/components/html/HTML.js#L33

This would either need to be a custom component override of this element or submit a pull request, but I would be concerned at how this may reduce performance of these elements.

Tooltips, this actually could be fixed and it would go here

https://github.com/formio/formio.js/blob/master/src/components/base/Base.js#L1203

Seems like this would need to be implemented as

```js
this.tooltip = new Tooltip(ttElement, {
      trigger: 'hover click',
      placement: 'right',
      html: true,
      title: this.t(component.tooltip).replace(/(?:\r\n|\r|\n)/g, '<br />')
    });
```

**Comment by airarrazaval** [comment]
@travist @cabrerabywaters I added the pull request https://github.com/formio/formio.js/pull/843. The tool tip has the issue of the line breaks, thus it should be treated (in my opinion) as the html component content and just interpolate.

**Comment by rohitsiddha** [comment]
still translation for tooltip is not working.
