### ISSUE TITLE
Select component from External Source (URL) Doesn't work when form is viewAsHtml

### ISSUE THREAD

**Issue by imadbakir** [formio/formio.js#846]
Hello, 
Select component from External Source (URL) Doesn't work when form is viewAsHtml,
I guess the Call to the api is  not being made?

**Comment by randallknutson** [comment]
Can you describe what you mean by it not working? When viewAsHtml is selected it is supposed to render it as HTML and not a form. Therefore the request to the server is never made and the value of the select component is rendered instead.

**Comment by imadbakir** [comment]
@ randallknutson hi, thanks for calirification, that helped me develop a work around for my case, 
but the problem still exists, which I will explain let's assume that we have a select that gets data from external URL and maps the Value to to item property called let's say "id" and is a number, say 15, 
when the select is rendered it will actually find the value 15 in the array of values and display the corresponding "label". 

now when the form is disabled, that code isn't executed resulting in a value that is a number, which is not a desired behaviour, 
and last, because value is a number it doesn't get returned by the function asString() as the code checks for string or object.

**Comment by travist** [comment]
We will add this to our backlog.

**Comment by randallknutson** [comment]
What do you think is the proper way to fix this? We're a little hesitant to add a request to the external URL during the html render event since that will slow everything down and force an internet connection to be able to render the html for a form. 

One way you can get this to work for now is to change from using a value property to saving the entire object. That way it is always available to render.

We may need to make a change around the asString() function to return the number as a string at the very least.

**Comment by imadbakir** [comment]
@randallknutson Exactly, that is what I did for now I'm storing the object, 
I think the asString() thing might be helpful too.
for now I went with the object option, but we still may need this, or someone else also might as well need it. 
I tried to make the request too, and it did slow everything down it also raised few other issues.
I agree with the asString Fix.

**Comment by randallknutson** [comment]
We've had discussions around this for a while since saving just the value of a property causes issues in other places as well when we don't have enough information to render the results. At some point we will come up with a better solution but it is a tricky one to solve. I'll open a ticket on the asString function.
