### ISSUE TITLE
Bug with radio group, ids not unique

### ISSUE THREAD

**Issue by pkochubey** [formio/formio.js#893]
Hi. Example:
http://jsfiddle.net/jg7n5tuh/

If we have on one page two forms with radio groups, after changed in second radio group, first radio group is empty.  

Video for example: https://yadi.sk/d/CiyCzOMe71CQLQ

**Comment by pkochubey** [comment]
src/utils/utils.js - getRandomComponentId()

**Comment by pkochubey** [comment]
> or are you embedding the exact same form twice?

**Comment by pkochubey** [comment]
@travist Hi, what do you think about this issue this is bug or feature? :)

**Comment by travist** [comment]
I am curious why the logic provided on this line is not working.

https://github.com/formio/formio.js/blob/master/src/components/radio/Radio.js#L61

What this does is append the component ID (which is auto-generated for every new instance of a component created) to the name of the radios. This would allow a form that is rendered twice on the page to not affect the other forms because new instances of the Radio component would be created. Looking at your HTML markup that is rendered, do you see the ID appended to the names of these Radios? If they are the same, then this makes me believe that there is an issue with how you are creating the form twice on the page.

**Comment by pkochubey** [comment]
Really interesting, in current time in jsfiddle.net issue not reproduced but I recorded on video 11 day later you can see it in my first message. Hmm, ok issue closed.
